
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-23T14:22:48+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "ef81d7344a651ebae38555b7e6389867c15aa907",
 "version": "2.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
