[tool.poetry]
name = "jcal"
version = "0.0.13"
authors = ["Saito Tsutomu <tsutomu7@hotmail.co.jp>"]
homepage = "https://github.com/SaitoTsutomu/jcal"
classifiers = [
   "Development Status :: 1 - Planning",
   "License :: OSI Approved :: Python Software Foundation License",
   "Programming Language :: Python",
   "Topic :: Software Development",
   "Topic :: Scientific/Engineering",
]
license = "PSFL"
readme = "README.rst"
description = "`jcal` is a package for Japanese holiday."

[tool.poetry.scripts]
jcal = "jcal:main"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.7.9"
black = "^19.10b0"
isort = "^4.3.21"
mypy = "^0.770"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
