[tool.poetry]
name = "mwdictionary"
version = "0.1.1"
description = "API Wrapper for the Merriam-Webster API."
authors = ["Peder Hovdan Andresen"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
httpx = "^0.12.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
