
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-17T16:44:02+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8279e091cd52ef496a9e585ae308d2ac25d39b52",
 "version": "4.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
