[tool.poetry]
name = "honestybox-measurement"
version = "1.0.4"
description = "A framework for measuring things and producing structured results."
authors = [
    "Honesty Box <engineering@honestybox.com.au>",
    "James Stewart <james@amorphitec.io>",
    "Stuart Dines <me@stuartdines.com>"
]
packages = [
    { include = "measurement" },
]
repository = "https://github.com/honesty-box/honestybox-measurement/"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.5"
validators = "^0.13.0"
dataclasses = {version = "^0.6.0", python = "^3.6.0"}
six = "^1.12"
speedtest-cli = "^2.1"
[tool.poetry.dev-dependencies]
pytest = "^3.0"
tox = "^3.13"
black = {version = "^18.3-alpha.0", allows-prereleases = true, python = ">=3.6"}
flake8 = "^3.7"
isort = "^4.3"
pytest-cov = "^2.7"
[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build=true
envlist = py35,py36,py37,py38
skipsdist = True

[testenv]
whitelist_externals = poetry
commands =
    poetry install -v
    poetry run pytest --cov
"""
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

