sudo: true
cache: pip
dist: xenial

language: python

python:
  - "3.7"

stages:
  - lint
  - docs
  - test

env:
  - TOXENV=py

jobs:
  include:
    # lint stage
    - stage: lint
      env: TOXENV=manifest
    - env: TOXENV=flake8
    - env: TOXENV=xenon
    - env: TOXENV=pyroma

    # docs stage
    - stage: docs
      env: TOXENV=doc8
    - env: TOXENV=readme
    - env: TOXENV=docs

    # test stage
    - stage: test
      env: TOXENV=py

matrix:
  allow_failures:
    - env: TOXENV=xenon

before_install:
  - pip install codecov coverage

install:
  - pip install tox

script:
  - tox

after_success:
  - tox -e coverage-report
  - codecov

notifications:
  slack: pybel:n2KbWKBum3musnBg3L76gGwq
