
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-22T17:37:35+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7d24c213bd26bc8411ba1939f826c75d9c6ada1b",
 "version": "0.1.3b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
