
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-24T14:15:09+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "50fb3a2a06f97744efefdbc1956e56d8c23f7955",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
