[tool.poetry]
name = "cognite-open-set-classifier"
version = "0.2.0"
description = "Open-set classifier"
authors = ["Rebecca Wiborg Seyfarth <rebecca.wiborg.seyfarth@cognite.com>"]

packages = [
    { include="cognite", from="." },
]

[tool.black]
line-length = 120
target_version = ['py37']
include = '\.py$'

[tool.isort]
line_length=120                # corresponds to -w  flag
multi_line_output=3            # corresponds to -m  flag
include_trailing_comma=true    # corresponds to -tc flag
skip_glob = '^((?!py$).)*$'    # this makes sort all Python files
known_third_party = ["dirty_cat", "joblib", "numpy", "pandas", "pytest", "sklearn", "tensorflow"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.0.3"
dirty-cat = "^0.0.5"
scikit-learn = "=0.20.3"
joblib = "^0.14.0"
tensorflow = "=2.1.0" # circular imports in 2.2 ?
tensorflow-estimator = "=2.1.0" # poetry bug makes it update to 2.2 even when tf is 2.1

[tool.poetry.dev-dependencies]
black = "^19.3b0"
isort = "^4.3"
pre-commit = "^1.18"
pytest = "^5.2"
pytest-cov = "^2.8"
twine = "^2.0"


[[tool.poetry.source]]
name = "snakepit"
url = "https://cognite.jfrog.io/cognite/api/pypi/snakepit/simple"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"