
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-23T14:12:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9149a2f049c1743f0aa67b77f1f2dbb27030ef49",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
