- project:
    templates:
      - tempest-plugin-jobs
      - check-requirements
    check:
      jobs:
        - barbican-simple-crypto-devstack-tempest
    gate:
      queue: barbican
      jobs:
        - barbican-simple-crypto-devstack-tempest
    experimental:
      jobs:
        - barbican-simple-crypto-devstack-tempest-py35
