[tool.poetry]
name = "teamtrain-sdk"
version = "0.1.2"
description = "Python tools for interacting with the TeamTrain SDK"
authors = ["Edd <edward.abrahamsen-mills@safetyculture.io>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.23.0"
coloredlogs = "^14.0"
pandas = "^1.0.3"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
export_all = "teamtrain_sdk.teamtrain:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
