language: python

git:
    depth: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - libxkbcommon-x11-0  # for Qt

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - SETUP_XVFB=True
        - TOXENV=''
        - TOXARGS='-v'
        - TOXPOSARGS=''

matrix:
    include:

        - python: 3.6
          env: TOXENV='py36-test-oldestdeps'
          name: "Python 3.6 and oldest versions of key dependencies"

        - python: 3.7
          env: TOXENV='py37-test'
          name: "Python 3.7 with required dependencies"

        - python: 3.8
          env: TOXENV='py38-test-devdeps'
          name: "Python 3.8 and dev versions of key dependencies"

        - python: 3.8
          env: TOXENV='build_docs'
          name: "Documentation"

        - python: 3.8
          env: TOXENV='codestyle'
          name: "Code style"

before_install:
    - export DISPLAY=:99.0
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset

script:
    - pip install tox
    - tox $TOXARGS -- $TOXPOSARGS

after_success:
    - pip install coveralls coverage
    - coverage combine .tmp/*/.coverage
    - coverage report
    - coveralls
