# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data/mesonui-layout/activity_main.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore
from PyQt5 import QtGui
from PyQt5 import QtWidgets


class Ui_Activity_Main_Window(object):
    def setupUi(self, Activity_Main_Window):
        Activity_Main_Window.setObjectName("Activity_Main_Window")
        Activity_Main_Window.resize(857, 643)
        Activity_Main_Window.setFocusPolicy(QtCore.Qt.StrongFocus)
        Activity_Main_Window.setStyleSheet("")
        Activity_Main_Window.setDocumentMode(True)
        Activity_Main_Window.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(Activity_Main_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.meson_logo = QtWidgets.QLabel(self.centralwidget)
        self.meson_logo.setGeometry(QtCore.QRect(20, 5, 81, 71))
        self.meson_logo.setAutoFillBackground(False)
        self.meson_logo.setText("")
        self.meson_logo.setPixmap(QtGui.QPixmap(":/icon/mesonui-icon/meson_modern.png"))
        self.meson_logo.setScaledContents(True)
        self.meson_logo.setObjectName("meson_logo")
        self.output_console_dashboard = QtWidgets.QGroupBox(self.centralwidget)
        self.output_console_dashboard.setGeometry(QtCore.QRect(-2, 390, 861, 171))
        self.output_console_dashboard.setFocusPolicy(QtCore.Qt.NoFocus)
        self.output_console_dashboard.setStyleSheet("")
        self.output_console_dashboard.setObjectName("output_console_dashboard")
        self.output_console = QtWidgets.QPlainTextEdit(self.output_console_dashboard)
        self.output_console.setGeometry(QtCore.QRect(20, 30, 821, 131))
        self.output_console.setStyleSheet("")
        self.output_console.setReadOnly(True)
        self.output_console.setPlainText("")
        self.output_console.setObjectName("output_console")
        self.intro_dashboard = QtWidgets.QGroupBox(self.centralwidget)
        self.intro_dashboard.setGeometry(QtCore.QRect(-1, 150, 861, 231))
        self.intro_dashboard.setStyleSheet("")
        self.intro_dashboard.setObjectName("intro_dashboard")
        self.tabWidget = QtWidgets.QTabWidget(self.intro_dashboard)
        self.tabWidget.setGeometry(QtCore.QRect(0, 30, 861, 201))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.buildoptions_list = QtWidgets.QListWidget(self.tab)
        self.buildoptions_list.setGeometry(QtCore.QRect(20, 0, 811, 171))
        self.buildoptions_list.setStyleSheet("")
        self.buildoptions_list.setFrameShape(QtWidgets.QFrame.Panel)
        self.buildoptions_list.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.buildoptions_list.setObjectName("buildoptions_list")
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.projectinfo_list = QtWidgets.QListWidget(self.tab_4)
        self.projectinfo_list.setGeometry(QtCore.QRect(20, 0, 811, 171))
        self.projectinfo_list.setStyleSheet("")
        self.projectinfo_list.setFrameShape(QtWidgets.QFrame.Panel)
        self.projectinfo_list.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.projectinfo_list.setObjectName("projectinfo_list")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.testsinfo_list = QtWidgets.QListWidget(self.tab_3)
        self.testsinfo_list.setGeometry(QtCore.QRect(20, 0, 811, 171))
        self.testsinfo_list.setStyleSheet("")
        self.testsinfo_list.setFrameShape(QtWidgets.QFrame.Panel)
        self.testsinfo_list.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.testsinfo_list.setObjectName("testsinfo_list")
        self.tabWidget.addTab(self.tab_3, "")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 80, 821, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vertical_control_panal_Layout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vertical_control_panal_Layout.setContentsMargins(0, 0, 0, 0)
        self.vertical_control_panal_Layout.setSpacing(1)
        self.vertical_control_panal_Layout.setObjectName("vertical_control_panal_Layout")
        self.horizontal_higher_control = QtWidgets.QHBoxLayout()
        self.horizontal_higher_control.setSpacing(5)
        self.horizontal_higher_control.setObjectName("horizontal_higher_control")
        self.control_push_init = QtWidgets.QPushButton(self.layoutWidget)
        self.control_push_init.setStyleSheet("")
        self.control_push_init.setObjectName("control_push_init")
        self.horizontal_higher_control.addWidget(self.control_push_init)
        self.control_push_setup = QtWidgets.QPushButton(self.layoutWidget)
        self.control_push_setup.setStyleSheet("")
        self.control_push_setup.setObjectName("control_push_setup")
        self.horizontal_higher_control.addWidget(self.control_push_setup)
        self.control_push_build = QtWidgets.QPushButton(self.layoutWidget)
        self.control_push_build.setStyleSheet("")
        self.control_push_build.setObjectName("control_push_build")
        self.horizontal_higher_control.addWidget(self.control_push_build)
        self.control_push_test = QtWidgets.QPushButton(self.layoutWidget)
        self.control_push_test.setStyleSheet("")
        self.control_push_test.setObjectName("control_push_test")
        self.horizontal_higher_control.addWidget(self.control_push_test)
        self.vertical_control_panal_Layout.addLayout(self.horizontal_higher_control)
        self.horizontal_lower_control = QtWidgets.QHBoxLayout()
        self.horizontal_lower_control.setSpacing(5)
        self.horizontal_lower_control.setObjectName("horizontal_lower_control")
        self.control_push_conf = QtWidgets.QPushButton(self.layoutWidget)
        self.control_push_conf.setStyleSheet("")
        self.control_push_conf.setObjectName("control_push_conf")
        self.horizontal_lower_control.addWidget(self.control_push_conf)
        self.control_push_dist = QtWidgets.QPushButton(self.layoutWidget)
        self.control_push_dist.setStyleSheet("")
        self.control_push_dist.setObjectName("control_push_dist")
        self.horizontal_lower_control.addWidget(self.control_push_dist)
        self.control_push_install = QtWidgets.QPushButton(self.layoutWidget)
        self.control_push_install.setStyleSheet("")
        self.control_push_install.setObjectName("control_push_install")
        self.horizontal_lower_control.addWidget(self.control_push_install)
        self.control_push_clean = QtWidgets.QPushButton(self.layoutWidget)
        self.control_push_clean.setStyleSheet("")
        self.control_push_clean.setObjectName("control_push_clean")
        self.horizontal_lower_control.addWidget(self.control_push_clean)
        self.vertical_control_panal_Layout.addLayout(self.horizontal_lower_control)
        self.label_sourcedir = QtWidgets.QLabel(self.centralwidget)
        self.label_sourcedir.setGeometry(QtCore.QRect(120, 20, 91, 21))
        self.label_sourcedir.setStyleSheet("")
        self.label_sourcedir.setObjectName("label_sourcedir")
        self.label_builddir = QtWidgets.QLabel(self.centralwidget)
        self.label_builddir.setGeometry(QtCore.QRect(120, 43, 91, 21))
        self.label_builddir.setObjectName("label_builddir")
        self.project_sourcedir = QtWidgets.QLineEdit(self.centralwidget)
        self.project_sourcedir.setGeometry(QtCore.QRect(210, 20, 571, 21))
        self.project_sourcedir.setStyleSheet("")
        self.project_sourcedir.setText("")
        self.project_sourcedir.setObjectName("project_sourcedir")
        self.control_push_open_sourcedir = QtWidgets.QPushButton(self.centralwidget)
        self.control_push_open_sourcedir.setGeometry(QtCore.QRect(790, 20, 51, 21))
        self.control_push_open_sourcedir.setStyleSheet("")
        self.control_push_open_sourcedir.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/mesonui-icon/ic_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.control_push_open_sourcedir.setIcon(icon)
        self.control_push_open_sourcedir.setObjectName("control_push_open_sourcedir")
        self.project_builddir = QtWidgets.QLineEdit(self.centralwidget)
        self.project_builddir.setGeometry(QtCore.QRect(210, 47, 571, 21))
        self.project_builddir.setStyleSheet("")
        self.project_builddir.setText("")
        self.project_builddir.setObjectName("project_builddir")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 561, 831, 32))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.control_push_wraptools = QtWidgets.QPushButton(self.layoutWidget1)
        self.control_push_wraptools.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../mesonui-icon/wrapdb_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.control_push_wraptools.setIcon(icon1)
        self.control_push_wraptools.setIconSize(QtCore.QSize(12, 12))
        self.control_push_wraptools.setAutoRepeatDelay(300)
        self.control_push_wraptools.setObjectName("control_push_wraptools")
        self.horizontalLayout.addWidget(self.control_push_wraptools)
        self.control_push_subprojects = QtWidgets.QPushButton(self.layoutWidget1)
        self.control_push_subprojects.setStyleSheet("")
        self.control_push_subprojects.setObjectName("control_push_subprojects")
        self.horizontalLayout.addWidget(self.control_push_subprojects)
        self.control_push_version = QtWidgets.QPushButton(self.layoutWidget1)
        self.control_push_version.setStyleSheet("")
        self.control_push_version.setObjectName("control_push_version")
        self.horizontalLayout.addWidget(self.control_push_version)
        self.control_push_intro = QtWidgets.QPushButton(self.layoutWidget1)
        self.control_push_intro.setStyleSheet("")
        self.control_push_intro.setObjectName("control_push_intro")
        self.horizontalLayout.addWidget(self.control_push_intro)
        self.control_push_clear_sourcedir = QtWidgets.QPushButton(self.centralwidget)
        self.control_push_clear_sourcedir.setGeometry(QtCore.QRect(790, 46, 51, 21))
        self.control_push_clear_sourcedir.setStyleSheet("")
        self.control_push_clear_sourcedir.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/mesonui-icon/ic_clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.control_push_clear_sourcedir.setIcon(icon2)
        self.control_push_clear_sourcedir.setObjectName("control_push_clear_sourcedir")
        Activity_Main_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Activity_Main_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 857, 22))
        self.menubar.setObjectName("menubar")
        self.menu_meson_actions = QtWidgets.QMenu(self.menubar)
        self.menu_meson_actions.setSeparatorsCollapsible(False)
        self.menu_meson_actions.setObjectName("menu_meson_actions")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        self.menu_ninja_commands = QtWidgets.QMenu(self.menubar)
        self.menu_ninja_commands.setObjectName("menu_ninja_commands")
        Activity_Main_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Activity_Main_Window)
        self.statusbar.setObjectName("statusbar")
        Activity_Main_Window.setStatusBar(self.statusbar)
        self.actionMeson_docs = QtWidgets.QAction(Activity_Main_Window)
        self.actionMeson_docs.setObjectName("actionMeson_docs")
        self.actionIssue_for_Meson = QtWidgets.QAction(Activity_Main_Window)
        self.actionIssue_for_Meson.setObjectName("actionIssue_for_Meson")
        self.actionIssue_for_Meson_UI = QtWidgets.QAction(Activity_Main_Window)
        self.actionIssue_for_Meson_UI.setObjectName("actionIssue_for_Meson_UI")
        self.actionMeson_QnA = QtWidgets.QAction(Activity_Main_Window)
        self.actionMeson_QnA.setObjectName("actionMeson_QnA")
        self.action_meson_init = QtWidgets.QAction(Activity_Main_Window)
        self.action_meson_init.setObjectName("action_meson_init")
        self.action_meson_setup = QtWidgets.QAction(Activity_Main_Window)
        self.action_meson_setup.setObjectName("action_meson_setup")
        self.action_meson_build = QtWidgets.QAction(Activity_Main_Window)
        self.action_meson_build.setObjectName("action_meson_build")
        self.action_meson_test = QtWidgets.QAction(Activity_Main_Window)
        self.action_meson_test.setObjectName("action_meson_test")
        self.action_meson_conf = QtWidgets.QAction(Activity_Main_Window)
        self.action_meson_conf.setObjectName("action_meson_conf")
        self.action_meson_dist = QtWidgets.QAction(Activity_Main_Window)
        self.action_meson_dist.setObjectName("action_meson_dist")
        self.action_meson_install = QtWidgets.QAction(Activity_Main_Window)
        self.action_meson_install.setObjectName("action_meson_install")
        self.action_meson_clean = QtWidgets.QAction(Activity_Main_Window)
        self.action_meson_clean.setObjectName("action_meson_clean")
        self.action_meson_wraptools = QtWidgets.QAction(Activity_Main_Window)
        self.action_meson_wraptools.setObjectName("action_meson_wraptools")
        self.action_meson_intro = QtWidgets.QAction(Activity_Main_Window)
        self.action_meson_intro.setObjectName("action_meson_intro")
        self.action_meson_version = QtWidgets.QAction(Activity_Main_Window)
        self.action_meson_version.setObjectName("action_meson_version")
        self.action_help = QtWidgets.QAction(Activity_Main_Window)
        self.action_help.setObjectName("action_help")
        self.action_open_sourcedir = QtWidgets.QAction(Activity_Main_Window)
        self.action_open_sourcedir.setObjectName("action_open_sourcedir")
        self.action_clear_sourcedir = QtWidgets.QAction(Activity_Main_Window)
        self.action_clear_sourcedir.setObjectName("action_clear_sourcedir")
        self.action_meson_subprojects = QtWidgets.QAction(Activity_Main_Window)
        self.action_meson_subprojects.setObjectName("action_meson_subprojects")
        self.action_meson_docs = QtWidgets.QAction(Activity_Main_Window)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/mesonui-icon/ic_docs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_meson_docs.setIcon(icon3)
        self.action_meson_docs.setObjectName("action_meson_docs")
        self.action_meson_issue = QtWidgets.QAction(Activity_Main_Window)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/mesonui-icon/ic_github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_meson_issue.setIcon(icon4)
        self.action_meson_issue.setObjectName("action_meson_issue")
        self.action_mesonui_issue = QtWidgets.QAction(Activity_Main_Window)
        self.action_mesonui_issue.setIcon(icon4)
        self.action_mesonui_issue.setObjectName("action_mesonui_issue")
        self.action_ninja_build = QtWidgets.QAction(Activity_Main_Window)
        self.action_ninja_build.setObjectName("action_ninja_build")
        self.action_ninja_test = QtWidgets.QAction(Activity_Main_Window)
        self.action_ninja_test.setObjectName("action_ninja_test")
        self.action_ninja_dist = QtWidgets.QAction(Activity_Main_Window)
        self.action_ninja_dist.setObjectName("action_ninja_dist")
        self.action_ninja_install = QtWidgets.QAction(Activity_Main_Window)
        self.action_ninja_install.setObjectName("action_ninja_install")
        self.action_ninja_clean = QtWidgets.QAction(Activity_Main_Window)
        self.action_ninja_clean.setObjectName("action_ninja_clean")
        self.action_ninja_version = QtWidgets.QAction(Activity_Main_Window)
        self.action_ninja_version.setObjectName("action_ninja_version")
        self.menu_meson_actions.addAction(self.action_open_sourcedir)
        self.menu_meson_actions.addAction(self.action_clear_sourcedir)
        self.menu_meson_actions.addSeparator()
        self.menu_meson_actions.addAction(self.action_meson_init)
        self.menu_meson_actions.addAction(self.action_meson_setup)
        self.menu_meson_actions.addAction(self.action_meson_build)
        self.menu_meson_actions.addAction(self.action_meson_test)
        self.menu_meson_actions.addAction(self.action_meson_conf)
        self.menu_meson_actions.addAction(self.action_meson_dist)
        self.menu_meson_actions.addAction(self.action_meson_install)
        self.menu_meson_actions.addAction(self.action_meson_clean)
        self.menu_meson_actions.addAction(self.action_meson_subprojects)
        self.menu_meson_actions.addAction(self.action_meson_wraptools)
        self.menu_meson_actions.addAction(self.action_meson_intro)
        self.menu_meson_actions.addAction(self.action_meson_version)
        self.menuhelp.addAction(self.action_meson_docs)
        self.menuhelp.addAction(self.action_meson_issue)
        self.menuhelp.addAction(self.action_mesonui_issue)
        self.menu_ninja_commands.addAction(self.action_ninja_build)
        self.menu_ninja_commands.addAction(self.action_ninja_test)
        self.menu_ninja_commands.addAction(self.action_ninja_dist)
        self.menu_ninja_commands.addAction(self.action_ninja_install)
        self.menu_ninja_commands.addAction(self.action_ninja_clean)
        self.menu_ninja_commands.addAction(self.action_ninja_version)
        self.menubar.addAction(self.menu_meson_actions.menuAction())
        self.menubar.addAction(self.menu_ninja_commands.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(Activity_Main_Window)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Activity_Main_Window)

    def retranslateUi(self, Activity_Main_Window):
        _translate = QtCore.QCoreApplication.translate
        Activity_Main_Window.setWindowTitle(_translate("Activity_Main_Window", "Meson-UI"))
        self.output_console_dashboard.setTitle(_translate("Activity_Main_Window", "Output Console:"))
        self.intro_dashboard.setTitle(_translate("Activity_Main_Window", "Introspection Dashboard:"))
        self.buildoptions_list.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Activity_Main_Window", "Meson Build Options"))
        self.projectinfo_list.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Activity_Main_Window", "Project Information"))
        self.testsinfo_list.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Activity_Main_Window", "Unit Tests"))
        self.control_push_init.setText(_translate("Activity_Main_Window", "Init Project"))
        self.control_push_setup.setText(_translate("Activity_Main_Window", "Setup Project"))
        self.control_push_build.setText(_translate("Activity_Main_Window", "Build Project"))
        self.control_push_test.setText(_translate("Activity_Main_Window", "Run Tests"))
        self.control_push_conf.setText(_translate("Activity_Main_Window", "Configure Project"))
        self.control_push_dist.setText(_translate("Activity_Main_Window", "Generate release"))
        self.control_push_install.setText(_translate("Activity_Main_Window", "Install Project"))
        self.control_push_clean.setText(_translate("Activity_Main_Window", "Clean Project"))
        self.label_sourcedir.setText(_translate("Activity_Main_Window", "Source dir:"))
        self.label_builddir.setText(_translate("Activity_Main_Window", "Build dir:"))
        self.control_push_wraptools.setText(_translate("Activity_Main_Window", "WrapDB Tools"))
        self.control_push_subprojects.setText(_translate("Activity_Main_Window", "Subprojects"))
        self.control_push_version.setText(_translate("Activity_Main_Window", "Version"))
        self.control_push_intro.setText(_translate("Activity_Main_Window", "Introspction Refresh"))
        self.menu_meson_actions.setTitle(_translate("Activity_Main_Window", "Meson commands"))
        self.menuhelp.setTitle(_translate("Activity_Main_Window", "help"))
        self.menu_ninja_commands.setTitle(_translate("Activity_Main_Window", "Ninja commands"))
        self.actionMeson_docs.setText(_translate("Activity_Main_Window", "Meson docs"))
        self.actionIssue_for_Meson.setText(_translate("Activity_Main_Window", "Issue for Meson"))
        self.actionIssue_for_Meson_UI.setText(_translate("Activity_Main_Window", "Issue for Meson-UI"))
        self.actionMeson_QnA.setText(_translate("Activity_Main_Window", "Meson QnA"))
        self.action_meson_init.setText(_translate("Activity_Main_Window", "Init new project"))
        self.action_meson_setup.setText(_translate("Activity_Main_Window", "Setup project"))
        self.action_meson_build.setText(_translate("Activity_Main_Window", "Compile project"))
        self.action_meson_test.setText(_translate("Activity_Main_Window", "Run tests"))
        self.action_meson_conf.setText(_translate("Activity_Main_Window", "Configure project"))
        self.action_meson_dist.setText(_translate("Activity_Main_Window", "Generate release"))
        self.action_meson_install.setText(_translate("Activity_Main_Window", "Install project"))
        self.action_meson_clean.setText(_translate("Activity_Main_Window", "Clean builddir"))
        self.action_meson_wraptools.setText(_translate("Activity_Main_Window", "Wrap tools"))
        self.action_meson_intro.setText(_translate("Activity_Main_Window", "Introspection refresh"))
        self.action_meson_version.setText(_translate("Activity_Main_Window", "Version"))
        self.action_help.setText(_translate("Activity_Main_Window", "Help"))
        self.action_open_sourcedir.setText(_translate("Activity_Main_Window", "Open sourcedir"))
        self.action_clear_sourcedir.setText(_translate("Activity_Main_Window", "Clear sourcedir"))
        self.action_meson_subprojects.setText(_translate("Activity_Main_Window", "Subprojects"))
        self.action_meson_docs.setText(_translate("Activity_Main_Window", "Meson docs"))
        self.action_meson_issue.setText(_translate("Activity_Main_Window", "Meson issue"))
        self.action_mesonui_issue.setText(_translate("Activity_Main_Window", "Meson-UI issue"))
        self.action_ninja_build.setText(_translate("Activity_Main_Window", "Build project"))
        self.action_ninja_test.setText(_translate("Activity_Main_Window", "Run tests"))
        self.action_ninja_dist.setText(_translate("Activity_Main_Window", "Generate release"))
        self.action_ninja_install.setText(_translate("Activity_Main_Window", "Install project"))
        self.action_ninja_clean.setText(_translate("Activity_Main_Window", "Clean project"))
        self.action_ninja_version.setText(_translate("Activity_Main_Window", "Version"))

try:
    from . import resource_rc

except ImportError:
    print(f'Resource not found in UI layout Main')
    print(f'Qt version {resource_rc.qt_version}')
