# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data/mesonui-layout/activity_conf.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_Activity_Configure_Dialog(object):
    def setupUi(self, Activity_Configure_Dialog):
        Activity_Configure_Dialog.setObjectName("Activity_Configure_Dialog")
        Activity_Configure_Dialog.resize(740, 421)
        Activity_Configure_Dialog.setStyleSheet("")
        self.groupBox = QtWidgets.QGroupBox(Activity_Configure_Dialog)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 741, 341))
        self.groupBox.setObjectName("groupBox")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setGeometry(QtCore.QRect(0, 30, 741, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.group_core = QtWidgets.QGroupBox(self.tab)
        self.group_core.setGeometry(QtCore.QRect(0, 0, 741, 291))
        self.group_core.setStyleSheet("")
        self.group_core.setObjectName("group_core")
        self.combo_buildtype = QtWidgets.QComboBox(self.group_core)
        self.combo_buildtype.setGeometry(QtCore.QRect(120, 100, 151, 21))
        self.combo_buildtype.setStyleSheet("")
        self.combo_buildtype.setObjectName("combo_buildtype")
        self.label = QtWidgets.QLabel(self.group_core)
        self.label.setGeometry(QtCore.QRect(19, 100, 71, 16))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.combo_auto_features = QtWidgets.QComboBox(self.group_core)
        self.combo_auto_features.setGeometry(QtCore.QRect(120, 40, 151, 21))
        self.combo_auto_features.setStyleSheet("")
        self.combo_auto_features.setObjectName("combo_auto_features")
        self.label_3 = QtWidgets.QLabel(self.group_core)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 91, 16))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.combo_default_library = QtWidgets.QComboBox(self.group_core)
        self.combo_default_library.setGeometry(QtCore.QRect(120, 130, 151, 21))
        self.combo_default_library.setStyleSheet("")
        self.combo_default_library.setObjectName("combo_default_library")
        self.label_4 = QtWidgets.QLabel(self.group_core)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 91, 16))
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.combo_layout = QtWidgets.QComboBox(self.group_core)
        self.combo_layout.setGeometry(QtCore.QRect(599, 100, 111, 21))
        self.combo_layout.setStyleSheet("")
        self.combo_layout.setObjectName("combo_layout")
        self.label_layout = QtWidgets.QLabel(self.group_core)
        self.label_layout.setGeometry(QtCore.QRect(549, 100, 51, 16))
        self.label_layout.setStyleSheet("")
        self.label_layout.setObjectName("label_layout")
        self.combo_wrap_mode = QtWidgets.QComboBox(self.group_core)
        self.combo_wrap_mode.setGeometry(QtCore.QRect(380, 70, 151, 21))
        self.combo_wrap_mode.setStyleSheet("")
        self.combo_wrap_mode.setObjectName("combo_wrap_mode")
        self.combo_unity = QtWidgets.QComboBox(self.group_core)
        self.combo_unity.setGeometry(QtCore.QRect(380, 100, 151, 21))
        self.combo_unity.setStyleSheet("")
        self.combo_unity.setObjectName("combo_unity")
        self.label_11 = QtWidgets.QLabel(self.group_core)
        self.label_11.setGeometry(QtCore.QRect(279, 70, 81, 16))
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.group_core)
        self.label_12.setGeometry(QtCore.QRect(278, 100, 81, 16))
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.combo_warnlevel = QtWidgets.QComboBox(self.group_core)
        self.combo_warnlevel.setGeometry(QtCore.QRect(380, 40, 151, 21))
        self.combo_warnlevel.setStyleSheet("")
        self.combo_warnlevel.setObjectName("combo_warnlevel")
        self.label_15 = QtWidgets.QLabel(self.group_core)
        self.label_15.setGeometry(QtCore.QRect(279, 40, 91, 16))
        self.label_15.setStyleSheet("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.group_core)
        self.label_16.setGeometry(QtCore.QRect(549, 40, 51, 16))
        self.label_16.setStyleSheet("")
        self.label_16.setObjectName("label_16")
        self.combo_werror = QtWidgets.QComboBox(self.group_core)
        self.combo_werror.setGeometry(QtCore.QRect(599, 40, 111, 21))
        self.combo_werror.setStyleSheet("")
        self.combo_werror.setObjectName("combo_werror")
        self.combo_strip = QtWidgets.QComboBox(self.group_core)
        self.combo_strip.setGeometry(QtCore.QRect(600, 70, 111, 21))
        self.combo_strip.setStyleSheet("")
        self.combo_strip.setObjectName("combo_strip")
        self.label_strip = QtWidgets.QLabel(self.group_core)
        self.label_strip.setGeometry(QtCore.QRect(549, 70, 51, 16))
        self.label_strip.setStyleSheet("")
        self.label_strip.setObjectName("label_strip")
        self.group_subcore = QtWidgets.QGroupBox(self.group_core)
        self.group_subcore.setGeometry(QtCore.QRect(0, 160, 741, 121))
        self.group_subcore.setStyleSheet("")
        self.group_subcore.setObjectName("group_subcore")
        self.edit_cmake_prefix_path = QtWidgets.QLineEdit(self.group_subcore)
        self.edit_cmake_prefix_path.setGeometry(QtCore.QRect(180, 40, 521, 21))
        self.edit_cmake_prefix_path.setStyleSheet("")
        self.edit_cmake_prefix_path.setText("")
        self.edit_cmake_prefix_path.setObjectName("edit_cmake_prefix_path")
        self.label_13 = QtWidgets.QLabel(self.group_subcore)
        self.label_13.setGeometry(QtCore.QRect(30, 40, 141, 16))
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.group_subcore)
        self.label_14.setGeometry(QtCore.QRect(30, 70, 131, 16))
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.edit_pkg_config_path = QtWidgets.QLineEdit(self.group_subcore)
        self.edit_pkg_config_path.setGeometry(QtCore.QRect(180, 70, 521, 21))
        self.edit_pkg_config_path.setStyleSheet("")
        self.edit_pkg_config_path.setText("")
        self.edit_pkg_config_path.setObjectName("edit_pkg_config_path")
        self.label_2 = QtWidgets.QLabel(self.group_core)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 91, 16))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.combo_fetal_warnings = QtWidgets.QComboBox(self.group_core)
        self.combo_fetal_warnings.setGeometry(QtCore.QRect(380, 130, 151, 21))
        self.combo_fetal_warnings.setStyleSheet("")
        self.combo_fetal_warnings.setObjectName("combo_fetal_warnings")
        self.label_5 = QtWidgets.QLabel(self.group_core)
        self.label_5.setGeometry(QtCore.QRect(280, 130, 91, 16))
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.combo_backend = QtWidgets.QComboBox(self.group_core)
        self.combo_backend.setGeometry(QtCore.QRect(120, 70, 151, 21))
        self.combo_backend.setStyleSheet("")
        self.combo_backend.setObjectName("combo_backend")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.group_base = QtWidgets.QGroupBox(self.tab_2)
        self.group_base.setGeometry(QtCore.QRect(0, 0, 741, 291))
        self.group_base.setObjectName("group_base")
        self.label_b_colorout = QtWidgets.QLabel(self.tab_2)
        self.label_b_colorout.setGeometry(QtCore.QRect(19, 40, 81, 16))
        self.label_b_colorout.setObjectName("label_b_colorout")
        self.label_b_lundef = QtWidgets.QLabel(self.tab_2)
        self.label_b_lundef.setGeometry(QtCore.QRect(20, 100, 91, 16))
        self.label_b_lundef.setObjectName("label_b_lundef")
        self.combo_b_pie = QtWidgets.QComboBox(self.tab_2)
        self.combo_b_pie.setGeometry(QtCore.QRect(360, 70, 90, 21))
        self.combo_b_pie.setObjectName("combo_b_pie")
        self.combo_b_coverage = QtWidgets.QComboBox(self.tab_2)
        self.combo_b_coverage.setGeometry(QtCore.QRect(120, 70, 90, 21))
        self.combo_b_coverage.setObjectName("combo_b_coverage")
        self.label_b_vscrt = QtWidgets.QLabel(self.tab_2)
        self.label_b_vscrt.setGeometry(QtCore.QRect(518, 100, 81, 16))
        self.label_b_vscrt.setObjectName("label_b_vscrt")
        self.combo_b_sanitize = QtWidgets.QComboBox(self.tab_2)
        self.combo_b_sanitize.setGeometry(QtCore.QRect(610, 70, 90, 21))
        self.combo_b_sanitize.setObjectName("combo_b_sanitize")
        self.combo_b_pgo = QtWidgets.QComboBox(self.tab_2)
        self.combo_b_pgo.setGeometry(QtCore.QRect(360, 40, 90, 21))
        self.combo_b_pgo.setObjectName("combo_b_pgo")
        self.combo_b_colorout = QtWidgets.QComboBox(self.tab_2)
        self.combo_b_colorout.setGeometry(QtCore.QRect(120, 40, 90, 21))
        self.combo_b_colorout.setObjectName("combo_b_colorout")
        self.label_b_coverage = QtWidgets.QLabel(self.tab_2)
        self.label_b_coverage.setGeometry(QtCore.QRect(20, 70, 91, 16))
        self.label_b_coverage.setObjectName("label_b_coverage")
        self.combo_b_vscrt = QtWidgets.QComboBox(self.tab_2)
        self.combo_b_vscrt.setGeometry(QtCore.QRect(610, 100, 90, 21))
        self.combo_b_vscrt.setObjectName("combo_b_vscrt")
        self.label_b_staticpic = QtWidgets.QLabel(self.tab_2)
        self.label_b_staticpic.setGeometry(QtCore.QRect(520, 40, 81, 16))
        self.label_b_staticpic.setObjectName("label_b_staticpic")
        self.combo_b_lundef = QtWidgets.QComboBox(self.tab_2)
        self.combo_b_lundef.setGeometry(QtCore.QRect(120, 100, 90, 21))
        self.combo_b_lundef.setObjectName("combo_b_lundef")
        self.label_b_pgo = QtWidgets.QLabel(self.tab_2)
        self.label_b_pgo.setGeometry(QtCore.QRect(279, 40, 81, 16))
        self.label_b_pgo.setObjectName("label_b_pgo")
        self.label_b_sanitize = QtWidgets.QLabel(self.tab_2)
        self.label_b_sanitize.setGeometry(QtCore.QRect(520, 70, 81, 16))
        self.label_b_sanitize.setObjectName("label_b_sanitize")
        self.label_b_pie = QtWidgets.QLabel(self.tab_2)
        self.label_b_pie.setGeometry(QtCore.QRect(279, 70, 81, 16))
        self.label_b_pie.setObjectName("label_b_pie")
        self.combo_b_staticpic = QtWidgets.QComboBox(self.tab_2)
        self.combo_b_staticpic.setGeometry(QtCore.QRect(610, 40, 90, 21))
        self.combo_b_staticpic.setObjectName("combo_b_staticpic")
        self.combo_b_ndebug = QtWidgets.QComboBox(self.tab_2)
        self.combo_b_ndebug.setGeometry(QtCore.QRect(120, 130, 90, 21))
        self.combo_b_ndebug.setObjectName("combo_b_ndebug")
        self.label_b_ndebug = QtWidgets.QLabel(self.tab_2)
        self.label_b_ndebug.setGeometry(QtCore.QRect(21, 130, 81, 16))
        self.label_b_ndebug.setObjectName("label_b_ndebug")
        self.label_b_lto = QtWidgets.QLabel(self.tab_2)
        self.label_b_lto.setGeometry(QtCore.QRect(281, 100, 71, 16))
        self.label_b_lto.setObjectName("label_b_lto")
        self.combo_b_pch = QtWidgets.QComboBox(self.tab_2)
        self.combo_b_pch.setGeometry(QtCore.QRect(360, 130, 90, 21))
        self.combo_b_pch.setObjectName("combo_b_pch")
        self.combo_b_lto = QtWidgets.QComboBox(self.tab_2)
        self.combo_b_lto.setGeometry(QtCore.QRect(360, 100, 90, 21))
        self.combo_b_lto.setObjectName("combo_b_lto")
        self.label_b_pch = QtWidgets.QLabel(self.tab_2)
        self.label_b_pch.setGeometry(QtCore.QRect(280, 130, 71, 16))
        self.label_b_pch.setObjectName("label_b_pch")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.group_test = QtWidgets.QGroupBox(self.tab_4)
        self.group_test.setGeometry(QtCore.QRect(0, 0, 741, 291))
        self.group_test.setObjectName("group_test")
        self.combo_stdsplit = QtWidgets.QComboBox(self.group_test)
        self.combo_stdsplit.setGeometry(QtCore.QRect(120, 70, 91, 21))
        self.combo_stdsplit.setObjectName("combo_stdsplit")
        self.label_errorlogs = QtWidgets.QLabel(self.group_test)
        self.label_errorlogs.setGeometry(QtCore.QRect(21, 40, 81, 16))
        self.label_errorlogs.setObjectName("label_errorlogs")
        self.combo_errorlogs = QtWidgets.QComboBox(self.group_test)
        self.combo_errorlogs.setGeometry(QtCore.QRect(120, 40, 91, 21))
        self.combo_errorlogs.setObjectName("combo_errorlogs")
        self.label_stdsplit = QtWidgets.QLabel(self.group_test)
        self.label_stdsplit.setGeometry(QtCore.QRect(20, 70, 81, 16))
        self.label_stdsplit.setObjectName("label_stdsplit")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.group_backend = QtWidgets.QGroupBox(self.tab_3)
        self.group_backend.setGeometry(QtCore.QRect(0, 0, 741, 291))
        self.group_backend.setObjectName("group_backend")
        self.label_backend_max_links = QtWidgets.QLabel(self.group_backend)
        self.label_backend_max_links.setGeometry(QtCore.QRect(21, 40, 131, 16))
        self.label_backend_max_links.setObjectName("label_backend_max_links")
        self.edit_backend_max_links = QtWidgets.QLineEdit(self.group_backend)
        self.edit_backend_max_links.setGeometry(QtCore.QRect(170, 40, 111, 21))
        self.edit_backend_max_links.setText("")
        self.edit_backend_max_links.setObjectName("edit_backend_max_links")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.group_path = QtWidgets.QGroupBox(self.tab_5)
        self.group_path.setGeometry(QtCore.QRect(0, 0, 741, 291))
        self.group_path.setObjectName("group_path")
        self.label_prexif = QtWidgets.QLabel(self.group_path)
        self.label_prexif.setGeometry(QtCore.QRect(21, 40, 121, 16))
        self.label_prexif.setObjectName("label_prexif")
        self.edit_prexif = QtWidgets.QLineEdit(self.group_path)
        self.edit_prexif.setGeometry(QtCore.QRect(150, 40, 201, 21))
        self.edit_prexif.setText("")
        self.edit_prexif.setObjectName("edit_prexif")
        self.label_bindir = QtWidgets.QLabel(self.group_path)
        self.label_bindir.setGeometry(QtCore.QRect(20, 70, 121, 16))
        self.label_bindir.setObjectName("label_bindir")
        self.edit_bindir = QtWidgets.QLineEdit(self.group_path)
        self.edit_bindir.setGeometry(QtCore.QRect(149, 70, 201, 21))
        self.edit_bindir.setText("")
        self.edit_bindir.setObjectName("edit_bindir")
        self.label_datadir = QtWidgets.QLabel(self.group_path)
        self.label_datadir.setGeometry(QtCore.QRect(21, 100, 131, 16))
        self.label_datadir.setObjectName("label_datadir")
        self.edit_datadir = QtWidgets.QLineEdit(self.group_path)
        self.edit_datadir.setGeometry(QtCore.QRect(150, 100, 201, 21))
        self.edit_datadir.setText("")
        self.edit_datadir.setObjectName("edit_datadir")
        self.label_includedir = QtWidgets.QLabel(self.group_path)
        self.label_includedir.setGeometry(QtCore.QRect(21, 130, 121, 16))
        self.label_includedir.setObjectName("label_includedir")
        self.edit_includedir = QtWidgets.QLineEdit(self.group_path)
        self.edit_includedir.setGeometry(QtCore.QRect(150, 130, 201, 21))
        self.edit_includedir.setText("")
        self.edit_includedir.setObjectName("edit_includedir")
        self.label_infodir = QtWidgets.QLabel(self.group_path)
        self.label_infodir.setGeometry(QtCore.QRect(21, 160, 121, 16))
        self.label_infodir.setObjectName("label_infodir")
        self.edit_infodir = QtWidgets.QLineEdit(self.group_path)
        self.edit_infodir.setGeometry(QtCore.QRect(150, 160, 201, 21))
        self.edit_infodir.setText("")
        self.edit_infodir.setObjectName("edit_infodir")
        self.label_libdir = QtWidgets.QLabel(self.group_path)
        self.label_libdir.setGeometry(QtCore.QRect(21, 190, 121, 16))
        self.label_libdir.setObjectName("label_libdir")
        self.edit_libdir = QtWidgets.QLineEdit(self.group_path)
        self.edit_libdir.setGeometry(QtCore.QRect(150, 190, 201, 21))
        self.edit_libdir.setText("")
        self.edit_libdir.setObjectName("edit_libdir")
        self.label_execlibdir = QtWidgets.QLabel(self.group_path)
        self.label_execlibdir.setGeometry(QtCore.QRect(20, 220, 131, 16))
        self.label_execlibdir.setObjectName("label_execlibdir")
        self.edit_libexecdir = QtWidgets.QLineEdit(self.group_path)
        self.edit_libexecdir.setGeometry(QtCore.QRect(149, 220, 201, 21))
        self.edit_libexecdir.setText("")
        self.edit_libexecdir.setObjectName("edit_libexecdir")
        self.label_errorlogs_10 = QtWidgets.QLabel(self.group_path)
        self.label_errorlogs_10.setGeometry(QtCore.QRect(391, 40, 131, 16))
        self.label_errorlogs_10.setObjectName("label_errorlogs_10")
        self.edit_localedir = QtWidgets.QLineEdit(self.group_path)
        self.edit_localedir.setGeometry(QtCore.QRect(520, 40, 201, 21))
        self.edit_localedir.setText("")
        self.edit_localedir.setObjectName("edit_localedir")
        self.label_errorlogs_11 = QtWidgets.QLabel(self.group_path)
        self.label_errorlogs_11.setGeometry(QtCore.QRect(391, 70, 131, 16))
        self.label_errorlogs_11.setObjectName("label_errorlogs_11")
        self.edit_localstatedir = QtWidgets.QLineEdit(self.group_path)
        self.edit_localstatedir.setGeometry(QtCore.QRect(520, 70, 201, 21))
        self.edit_localstatedir.setText("")
        self.edit_localstatedir.setObjectName("edit_localstatedir")
        self.label_errorlogs_12 = QtWidgets.QLabel(self.group_path)
        self.label_errorlogs_12.setGeometry(QtCore.QRect(391, 100, 121, 16))
        self.label_errorlogs_12.setObjectName("label_errorlogs_12")
        self.edit_mandir = QtWidgets.QLineEdit(self.group_path)
        self.edit_mandir.setGeometry(QtCore.QRect(520, 100, 201, 21))
        self.edit_mandir.setText("")
        self.edit_mandir.setObjectName("edit_mandir")
        self.label_errorlogs_13 = QtWidgets.QLabel(self.group_path)
        self.label_errorlogs_13.setGeometry(QtCore.QRect(390, 130, 131, 16))
        self.label_errorlogs_13.setObjectName("label_errorlogs_13")
        self.edit_sbindir = QtWidgets.QLineEdit(self.group_path)
        self.edit_sbindir.setGeometry(QtCore.QRect(519, 130, 201, 21))
        self.edit_sbindir.setText("")
        self.edit_sbindir.setObjectName("edit_sbindir")
        self.label_errorlogs_14 = QtWidgets.QLabel(self.group_path)
        self.label_errorlogs_14.setGeometry(QtCore.QRect(390, 190, 131, 16))
        self.label_errorlogs_14.setObjectName("label_errorlogs_14")
        self.edit_sysconfdir = QtWidgets.QLineEdit(self.group_path)
        self.edit_sysconfdir.setGeometry(QtCore.QRect(519, 190, 201, 21))
        self.edit_sysconfdir.setText("")
        self.edit_sysconfdir.setObjectName("edit_sysconfdir")
        self.edit_sharedstatedir = QtWidgets.QLineEdit(self.group_path)
        self.edit_sharedstatedir.setGeometry(QtCore.QRect(519, 160, 201, 21))
        self.edit_sharedstatedir.setText("")
        self.edit_sharedstatedir.setObjectName("edit_sharedstatedir")
        self.label_errorlogs_15 = QtWidgets.QLabel(self.group_path)
        self.label_errorlogs_15.setGeometry(QtCore.QRect(390, 160, 121, 16))
        self.label_errorlogs_15.setObjectName("label_errorlogs_15")
        self.tabWidget.addTab(self.tab_5, "")
        self.layoutWidget = QtWidgets.QWidget(Activity_Configure_Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(380, 360, 352, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.control_push_do_update = QtWidgets.QPushButton(self.layoutWidget)
        self.control_push_do_update.setObjectName("control_push_do_update")
        self.horizontalLayout.addWidget(self.control_push_do_update)
        self.control_push_do_setup = QtWidgets.QPushButton(self.layoutWidget)
        self.control_push_do_setup.setDefault(True)
        self.control_push_do_setup.setObjectName("control_push_do_setup")
        self.horizontalLayout.addWidget(self.control_push_do_setup)
        self.control_push_no_setup = QtWidgets.QPushButton(Activity_Configure_Dialog)
        self.control_push_no_setup.setGeometry(QtCore.QRect(30, 364, 181, 24))
        self.control_push_no_setup.setObjectName("control_push_no_setup")

        self.retranslateUi(Activity_Configure_Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Activity_Configure_Dialog)

    def retranslateUi(self, Activity_Configure_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Activity_Configure_Dialog.setWindowTitle(_translate("Activity_Configure_Dialog", "Configure Dialog"))
        self.groupBox.setTitle(_translate("Activity_Configure_Dialog", "Configure view:"))
        self.group_core.setTitle(_translate("Activity_Configure_Dialog", "Configure any of the values for Meson built-in (Core options):"))
        self.label.setText(_translate("Activity_Configure_Dialog", "buildtype:"))
        self.label_3.setText(_translate("Activity_Configure_Dialog", "auto_features:"))
        self.label_4.setText(_translate("Activity_Configure_Dialog", "default_library:"))
        self.label_layout.setText(_translate("Activity_Configure_Dialog", "layout:"))
        self.label_11.setText(_translate("Activity_Configure_Dialog", "wrap_mode:"))
        self.label_12.setText(_translate("Activity_Configure_Dialog", "unity:"))
        self.label_15.setText(_translate("Activity_Configure_Dialog", "warning_level:"))
        self.label_16.setText(_translate("Activity_Configure_Dialog", "werror:"))
        self.label_strip.setText(_translate("Activity_Configure_Dialog", "strip:"))
        self.group_subcore.setTitle(_translate("Activity_Configure_Dialog", "Directory Prefix Values"))
        self.label_13.setText(_translate("Activity_Configure_Dialog", "cmake_prefix_path:"))
        self.label_14.setText(_translate("Activity_Configure_Dialog", "pkg_config_path:"))
        self.label_2.setText(_translate("Activity_Configure_Dialog", "backend:"))
        self.label_5.setText(_translate("Activity_Configure_Dialog", "fatal_warnings:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Activity_Configure_Dialog", "Core"))
        self.group_base.setTitle(_translate("Activity_Configure_Dialog", "Configure any of the values for Meson built-in (Base options):"))
        self.label_b_colorout.setText(_translate("Activity_Configure_Dialog", "b_colorout:"))
        self.label_b_lundef.setText(_translate("Activity_Configure_Dialog", "b_lundef:"))
        self.label_b_vscrt.setText(_translate("Activity_Configure_Dialog", "b_vscrt:"))
        self.label_b_coverage.setText(_translate("Activity_Configure_Dialog", "b_coverage:"))
        self.label_b_staticpic.setText(_translate("Activity_Configure_Dialog", "b_staticpic:"))
        self.label_b_pgo.setText(_translate("Activity_Configure_Dialog", "b_pgo:"))
        self.label_b_sanitize.setText(_translate("Activity_Configure_Dialog", "b_sanitize:"))
        self.label_b_pie.setText(_translate("Activity_Configure_Dialog", "b_pie:"))
        self.label_b_ndebug.setText(_translate("Activity_Configure_Dialog", "b_ndebug:"))
        self.label_b_lto.setText(_translate("Activity_Configure_Dialog", "b_lto:"))
        self.label_b_pch.setText(_translate("Activity_Configure_Dialog", "b_pch:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Activity_Configure_Dialog", "Base"))
        self.group_test.setTitle(_translate("Activity_Configure_Dialog", "Configure any of the values for Meson built-in (Test options):"))
        self.label_errorlogs.setText(_translate("Activity_Configure_Dialog", "errorlogs:"))
        self.label_stdsplit.setText(_translate("Activity_Configure_Dialog", "stdsplit:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Activity_Configure_Dialog", "Test"))
        self.group_backend.setTitle(_translate("Activity_Configure_Dialog", "Configure any of the values for Meson built-in (Backend options):"))
        self.label_backend_max_links.setText(_translate("Activity_Configure_Dialog", "backend_max_links:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Activity_Configure_Dialog", "Backend"))
        self.group_path.setTitle(_translate("Activity_Configure_Dialog", "Configure any of the values for Meson built-in (Directory options):"))
        self.label_prexif.setText(_translate("Activity_Configure_Dialog", "prefix:"))
        self.label_bindir.setText(_translate("Activity_Configure_Dialog", "bindir:"))
        self.label_datadir.setText(_translate("Activity_Configure_Dialog", "datadir:"))
        self.label_includedir.setText(_translate("Activity_Configure_Dialog", "includedir:"))
        self.label_infodir.setText(_translate("Activity_Configure_Dialog", "infodir:"))
        self.label_libdir.setText(_translate("Activity_Configure_Dialog", "libdir:"))
        self.label_execlibdir.setText(_translate("Activity_Configure_Dialog", "libexecdir:"))
        self.label_errorlogs_10.setText(_translate("Activity_Configure_Dialog", "localedir:"))
        self.label_errorlogs_11.setText(_translate("Activity_Configure_Dialog", "localstatedir:"))
        self.label_errorlogs_12.setText(_translate("Activity_Configure_Dialog", "mandir:"))
        self.label_errorlogs_13.setText(_translate("Activity_Configure_Dialog", "sbindir:"))
        self.label_errorlogs_14.setText(_translate("Activity_Configure_Dialog", "sysconfdir:"))
        self.label_errorlogs_15.setText(_translate("Activity_Configure_Dialog", "sharedstatedir:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Activity_Configure_Dialog", "Directory"))
        self.control_push_do_update.setText(_translate("Activity_Configure_Dialog", "Apply Current Settings"))
        self.control_push_do_setup.setText(_translate("Activity_Configure_Dialog", "Configure My Project"))
        self.control_push_no_setup.setText(_translate("Activity_Configure_Dialog", "Don\'t Not Configure Yet"))
