# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data/mesonui-layout/activity_init.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore
from PyQt5 import QtGui
from PyQt5 import QtWidgets


class Ui_Activity_Init_Dialog:
    def setupUi(self, Activity_Init_Dialog):
        Activity_Init_Dialog.setObjectName("Activity_Init_Dialog")
        Activity_Init_Dialog.resize(740, 421)
        Activity_Init_Dialog.setStyleSheet("")
        self.layoutWidget = QtWidgets.QWidget(Activity_Init_Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(370, 360, 364, 32))
        self.layoutWidget.setStyleSheet("")
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.control_push_do_update = QtWidgets.QPushButton(self.layoutWidget)
        self.control_push_do_update.setStyleSheet("")
        self.control_push_do_update.setObjectName("control_push_do_update")
        self.horizontalLayout.addWidget(self.control_push_do_update)
        self.control_push_do_init = QtWidgets.QPushButton(self.layoutWidget)
        self.control_push_do_init.setStyleSheet("")
        self.control_push_do_init.setObjectName("control_push_do_init")
        self.horizontalLayout.addWidget(self.control_push_do_init)
        self.groupBox = QtWidgets.QGroupBox(Activity_Init_Dialog)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 741, 351))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 81, 71))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icon/mesonui-icon/meson_modern.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.combo_type = QtWidgets.QComboBox(self.groupBox)
        self.combo_type.setGeometry(QtCore.QRect(140, 250, 191, 26))
        self.combo_type.setStyleSheet("")
        self.combo_type.setObjectName("combo_type")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 250, 101, 16))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 290, 101, 20))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.combo_lang = QtWidgets.QComboBox(self.groupBox)
        self.combo_lang.setGeometry(QtCore.QRect(140, 290, 191, 26))
        self.combo_lang.setStyleSheet("")
        self.combo_lang.setObjectName("combo_lang")
        self.edit_name = QtWidgets.QLineEdit(self.groupBox)
        self.edit_name.setGeometry(QtCore.QRect(140, 170, 191, 21))
        self.edit_name.setStyleSheet("")
        self.edit_name.setText("")
        self.edit_name.setObjectName("edit_name")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 101, 16))
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(30, 210, 101, 16))
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.edit_version = QtWidgets.QLineEdit(self.groupBox)
        self.edit_version.setGeometry(QtCore.QRect(140, 210, 191, 21))
        self.edit_version.setStyleSheet("")
        self.edit_version.setText("")
        self.edit_version.setObjectName("edit_version")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(340, 290, 381, 21))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(340, 250, 381, 16))
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(340, 210, 381, 21))
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(340, 170, 381, 21))
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.info = QtWidgets.QPlainTextEdit(self.groupBox)
        self.info.setGeometry(QtCore.QRect(140, 40, 571, 111))
        self.info.setStyleSheet("")
        self.info.setReadOnly(True)
        self.info.setObjectName("info")
        self.control_push_no_init = QtWidgets.QPushButton(Activity_Init_Dialog)
        self.control_push_no_init.setGeometry(QtCore.QRect(20, 365, 168, 24))
        self.control_push_no_init.setStyleSheet("")
        self.control_push_no_init.setObjectName("control_push_no_init")

        self.retranslateUi(Activity_Init_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Activity_Init_Dialog)

    def retranslateUi(self, Activity_Init_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Activity_Init_Dialog.setWindowTitle(_translate("Activity_Init_Dialog", "Dialog"))
        self.control_push_do_update.setText(_translate("Activity_Init_Dialog", "Apply Current Settings"))
        self.control_push_do_init.setText(_translate("Activity_Init_Dialog", "Create My New Project"))
        self.groupBox.setTitle(_translate("Activity_Init_Dialog", "Init view:"))
        self.label.setText(_translate("Activity_Init_Dialog", "project type:"))
        self.label_2.setText(_translate("Activity_Init_Dialog", "language:"))
        self.label_4.setText(_translate("Activity_Init_Dialog", "project name:"))
        self.label_6.setText(_translate("Activity_Init_Dialog", "version:"))
        self.label_3.setText(_translate("Activity_Init_Dialog", "project language. default: autodetected based on source files:"))
        self.label_8.setText(_translate("Activity_Init_Dialog", "project type. default: executable based project:"))
        self.label_10.setText(_translate("Activity_Init_Dialog", "project version. default: 0.1"))
        self.label_11.setText(_translate("Activity_Init_Dialog", "project name. default: demo"))
        self.info.setPlainText(_translate("Activity_Init_Dialog", "To make it easier for new developers to start working, Meson ships a tool to generate the basic setup of different kinds of projects. This functionality can be accessed with the meson init command.  Meson-UI supports this feature in the background:"))
        self.control_push_no_init.setText(_translate("Activity_Init_Dialog", "Don\'t Not Setup Yet"))

try:
    from . import resource_rc
except ImportError:
    print(f'Resource not found in UI layout Main')
    print(f'Qt version {resource_rc.qt_version}')
