[tool.poetry]
name = "django_magic"
version = "0.3a"
description = "A collection of simple helpers and utilities for Django web development"
authors = ["Jeremy Potter <git@stormdesign.us>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"
django = "^3.0.5"
dj_database_url = "^0.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
