[tool.poetry]
name = "ariadne-extended"
version = "0.1.0"
description = ""
authors = ["Patrick Forringer <pforringer@patriotrc.com>", "Buddy Lindsey <blindsey@patriotrc.com"]

[tool.poetry.dependencies]
python = "^3.7"
ariadne = "^0.11.0"
django = {version = ">=2.2, <3.1", optional = true}
pyhumps = "^1.3.1"
django-filter = {version = "^2.2.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
django = "^2.2"
model-bakery = "^1.1.0"
djangorestframework = "^3.11.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
target-version = ['py38']
line-length = 99
exclude = '''
(
  /(
    | \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
  )/
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
skip = "migrations"
