# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='vaa',
    version='0.2.0',
    description='Validators Adapter. The common interface for all validators.',
    project_urls={"homepage": "https://github.com/life4/vaa"},
    author='Gram Orsinium',
    author_email='master_fess@mail.ru',
    classifiers=[
        'Development Status :: 5 - Production/Stable', 'Environment :: Console',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3', 'Programming Language :: Python',
        'Topic :: Software Development :: Libraries :: Python Modules'
    ],
    packages=['vaa'],
    package_dir={"": "."},
    package_data={},
    install_requires=[],
    extras_require={
        "tests": ["pytest"],
        "validators": [
            "cerberus", "django", "djangorestframework", "marshmallow>=3.0.1",
            "pyschemes", "wtforms"
        ]
    },
)
