piece:
  tonic: C
  scale_type: major
  n_measures: 16
  max_skip: 3
  line_specifications:
    - lowest_note: C4
      highest_note: C5
      start_note: G4
      end_note: C4
    - lowest_note: G4
      highest_note: C6
      start_note: C5
      end_note: C5
  voice_leading_rules:
    names:
      - rearticulation
      - destination_of_skip
      - turn_after_skip
      - VI_VII_resolution
      - step_motion_to_end
    params:
      turn_after_skip:
        min_n_scale_degrees: 3
      step_motion_to_end:
        prohibit_rearticulation: true
  harmony_rules:
    names:
      - consonance
      - absence_of_large_intervals
      - absence_of_pitch_class_clashes
    params:
      absence_of_large_intervals:
        max_n_semitones: 16
  rendering_params:
    dir: rlmusician_data
    measure_in_seconds: 1.0
    midi:
      instrument: 0
      velocity: 100
    sinethesizer:
      timbre: default_timbre
      volume: 0.3
environment:
  observation_decay: 0.75
  reward_for_dead_end: -3
  scoring_coefs:
    climax_explicity: 3
    looped_pitches: 1
    looped_fragments: 1
    lines_correlation: 1
    types_of_motion: 1
    number_of_skips: 1
    downward_skips: 0.05
  scoring_fn_params:
    climax_explicity:
      shortage_penalty: 0.3
      duplication_penalty: 0.5
    looped_pitches:
      max_n_repetitions: 2
    types_of_motion:
      parallel_coef: -1
      similar_coef: -0.5
      oblique_coef: 0
      contrary_coef: 1
    number_of_skips:
      min_n_skips: 1
      max_n_skips: 3
    downward_skips:
      size_penalty_power: 2.0
agent:
  beam_width: 5
  n_records_to_keep: 5000
  n_trials_schedule:
    - 10000
    - 10000
    - 10000
    - 5000
    - 5000
    - 5000
    - 1000
  paralleling_params:
    n_processes:
