[tool.poetry]
name = "isingm"
version = "1.0.0"
description = "A pythonic Ising model simulation"
authors = ["Pacidus <pacidus@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.18.2"
matplotlib = "^3.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
