[tool.poetry]
name = "plogchain"
version = "0.0.1"
description = "Python Logging based on blockchain"

license = "ISC"

authors = [
	"Gg Math <g@gmath.io>"
]

readme = "README.md"

repository = "https://github.com/gg-math/plogchain"
homepage = "https://gg-math.github.io/plogchain"

keywords = ["logging", "security", "secure", "blockchain", "signature"]

[tool.poetry.dependencies]
python = "^3.2"
toml = "^0.9"


[tool.poetry.dev-dependencies]

[tool.poetry.scripts]

