[tool.poetry]
name = "pg-es-fdw"
version = "0.7.0"
description = "Connect PostgreSQL and Elastic Search with this Foreign Data Wrapper"
authors = ["Matthew Franglen <matthew@franglen.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
elasticsearch = "^7.6.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pylint = "^2.4.4"
pytest = "^5.4.1"
sh = "^1.12.14"
docker-compose = "^1.25.4"
psycopg2 = "^2.8.5"
ipython = "^7.13.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
