# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from api.media_type_api import MediaTypeApi  # noqa: E501
from tator.rest import ApiException


class TestMediaTypeApi(unittest.TestCase):
    """MediaTypeApi unit test stubs"""

    def setUp(self):
        self.api = api.media_type_api.MediaTypeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_entity_type_media_base(self):
        """Test case for create_entity_type_media_base

        """
        pass

    def test_destroy_entity_type_media(self):
        """Test case for destroy_entity_type_media

        """
        pass

    def test_partial_update_entity_type_media(self):
        """Test case for partial_update_entity_type_media

        """
        pass

    def test_retrieve_entity_type_media(self):
        """Test case for retrieve_entity_type_media

        """
        pass

    def test_retrieve_entity_type_media_base(self):
        """Test case for retrieve_entity_type_media_base

        """
        pass

    def test_update_entity_type_media(self):
        """Test case for update_entity_type_media

        """
        pass


if __name__ == '__main__':
    unittest.main()
