language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -U setuptools
- pip install tox-travis
script:
- export CURRENT_BRANCH=$(if [ -n "$TRAVIS_TAG" ]; then echo "master"; else echo "$TRAVIS_BRANCH"; fi)
- tox
after_success: python setup.py sdist bdist_wheel
deploy:
  - provider: releases
    api_key:
      secure: VgY978QLHZDi+O3oQms2BEY55i46L+G/pRa3tDl1URMxjL29K4bre4zQxnZlsVDwixA84h+ETY4TF9PTTrhTdkenpMrOxDzD+G95JKYXUMb/wbz6TdRKGh7Op/KMA7YoQR60goQz0CNAc0ZO1cNQaOPBin/vD5xlkZnTd1tsK0YGbuEOOB5nZ2IhCue9B1kwqOE0CuMGtcbbms0hRf3L/8pQtUA6kp7+5m69D4PN/J8ipzbhqozHoQnjN30KBdT1STYDKwpBjzb6c3nU0GdiWynjecaeqM4854JDfD9qZe98pYiQzFl7i6utqFUgRLB9RbC91SgQmNkSbkHWJlLoEgJBIZF0vD1HAPRsloWz+2jfO6fR2P/0RjcmmnFs+XFaQKoirniobGJKGRbvdbWIgS0HXJXFRwyxo0O7hjSLdLC2Kwo7x4xEQrdEgF3ZRPQOYyiU17CrfA8Zc+pqqkiT4GGonPKY9c6yEqkSwsfts9eiifdKKf6lT2+DgI/2fW/sqX9ZnrKTjwNo0nheRSLm0i+oy67r2j0cxP27kFDNuxt9KgvmXBeNak09+v/9N3U9AybLI7baRaUGbNeL3h5nSMRSVfR4PlelnEMkYFv6RS8+Z3yGBXTxMjUnI2A+FFgM8dRHTQsKmdwruO7k1jQAiZEuU+5SZXdr4Ra51TeO4XA=
    skip_cleanup: true
    file_glob: true
    file:
    - "dist/trakt-tools-*"
    - "dist/trakt_tools-*"
    on:
      repo: fuzeman/trakt-tools
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
      tags: true
  - provider: pypi
    user: fm-build
    password:
      secure: sd9kkBhUT63q/5ZoJ34FZb5VG49e/I4KqCIxWBmlKgMQCStlnFGz40jCOh1lPm0xAJBXYi2E+mXMylI+4ZzHiwGpCu7qWgx9cibDLPsuniHCPUfzYtaUb/k0jBM/eUrUKA3AMnKEoBKuy2p3F3nrJdw8R2l4G1Rt8RZ0pqTfX37tY/R57zE1Ms3EGM+jhAstCxntqR9C850vy3Z+uEPPHtH4Zvz/voJqW7Wvi+t4euea3+IzRRUBkArbOsw4bHTMKuSxZOFGVX3FBbfHSfWncvwNCeAdlSXtZbAD5R2mx+bBVZDIt3lclwj+RGVU5TrhbZmrqWz06hlmCMmSsTmD900Ox5QYCiiCgHJM+4tY5yw6uYVnRQjRcCn4ZUBFwj4PjdlIlRhtSkZ3C4lePu5eNTa0PV5tgywn8aGEFa04DohhOytD0XzpJRmLildLFIUJhVgxmyxhsq7ie+Ju7KSPcweVNF/lvttSDLSwyNqR1njj7Z9ggilDUw8s+gSTkRiVvP729r0rWKYVtSQuiVdJ5Lv+so6Ng1C3Kg28L60AqJyB+eEZ7vqPlD/NXSU0JAQvbuFqHuzsAw+J0jvTrk33FhyjW+RCPp7isjE9NIwLclj2A3vW8vNfQmfy21ppiMmPK7Il8zx11DclWStT+XUErPvuGzlvwh1vXfzsky+d5BA=
    skip_cleanup: true
    on:
      distributions: sdist bdist_wheel
      repo: fuzeman/trakt-tools
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
      tags: true
