# coding: utf-8

"""
    Snøskredvarsel API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v5.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Advice(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'advice_id': 'int',
        'image_url': 'str',
        'text': 'str'
    }

    attribute_map = {
        'advice_id': 'AdviceID',
        'image_url': 'ImageUrl',
        'text': 'Text'
    }

    def __init__(self, advice_id=None, image_url=None, text=None):  # noqa: E501
        """Advice - a model defined in Swagger"""  # noqa: E501
        self._advice_id = None
        self._image_url = None
        self._text = None
        self.discriminator = None
        if advice_id is not None:
            self.advice_id = advice_id
        if image_url is not None:
            self.image_url = image_url
        if text is not None:
            self.text = text

    @property
    def advice_id(self):
        """Gets the advice_id of this Advice.  # noqa: E501


        :return: The advice_id of this Advice.  # noqa: E501
        :rtype: int
        """
        return self._advice_id

    @advice_id.setter
    def advice_id(self, advice_id):
        """Sets the advice_id of this Advice.


        :param advice_id: The advice_id of this Advice.  # noqa: E501
        :type: int
        """

        self._advice_id = advice_id

    @property
    def image_url(self):
        """Gets the image_url of this Advice.  # noqa: E501


        :return: The image_url of this Advice.  # noqa: E501
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url):
        """Sets the image_url of this Advice.


        :param image_url: The image_url of this Advice.  # noqa: E501
        :type: str
        """

        self._image_url = image_url

    @property
    def text(self):
        """Gets the text of this Advice.  # noqa: E501


        :return: The text of this Advice.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this Advice.


        :param text: The text of this Advice.  # noqa: E501
        :type: str
        """

        self._text = text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Advice, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Advice):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
