ADCO_DESCRIPTION = "Adresse du compteur ADCO"
OPTARIF_DESCRIPTION = "Option tarifaire choisie"
ISOUSC_DESCRIPTION = "Intensité souscrite"
BASE_DESCRIPTION = "Index Base"
HCHC_DESCRIPTION = "Index Heures Creuses"
HCHP_DESCRIPTION = "Index Heures Pleines"
PTEC_DESCRIPTION = "Période Tarifaire en cours "
IINST_DESCRIPTION = "Intensité Instantanée"
IINST1_DESCRIPTION = "Courant efficace phase 1 (A)"
IINST2_DESCRIPTION = "Courant efficace phase 2 (A)"
IINST3_DESCRIPTION = "Courant efficace phase 3 (A)"
IMAX_DESCRIPTION = "Intensité maximale appelée"
IMAX1_DESCRIPTION = "Courant max phase 1 (A), toujours 60A en triphasé"
IMAX2_DESCRIPTION = "Courant max phase 2 (A), toujours 60A en triphasé"
IMAX3_DESCRIPTION = "Courant max phase 3 (A), toujours 60A en triphasé"
PMAX_DESCRIPTION = "Puissance maximale triphasée atteinte, valeur du jour n-1"
PAPP_DESCRIPTION = "Puissance apparente"
HHPHC_DESCRIPTION = "Horaire Heures Pleines Heures Creuses"
MOTDETAT_DESCRIPTION = "Mot d'état du compteur MOTDETAT"
PPOT_DESCRIPTION = "Présence des potentiels, 0X le X reflétant les coupures de phase selon la règle suivante: absence de la phase n -> bit n = 1"

UNIT_NONE = ""
UNIT_VA = "VA"
UNIT_WH = "Wh"
UNIT_A = "A"
