[tool.poetry]
name = "gandi"
version = "0.1.0"
description = ""
authors = ["Greg Anders <greg@gpanders.com>"]

[tool.poetry.scripts]
gandi = "gandi.console:run"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
