name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
    - name: remove label
      uses: actions/github-script@0.9.0
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |

          // Fetch the list of labels attached to the issue that
          // triggered the workflow
          const opts = github.issues.listLabelsOnIssue.endpoint.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
          });
          const labels = await github.paginate(opts);

          for (const label of labels) {
            // If the issue has a label named 'tests-passed', remove it
            if (label.name === 'tests-passed') {
              await github.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: 'tests-passed'
              })
              return;
            }
          }

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7.17
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo pip install strato-skipper
        mkdir -p ~/.docker
        echo "{}" > ~/.docker/config.json
        touch ${HOME}/.gitconfig
    - name: test
      run: |
        skipper make all
    - name: apply label
      uses: actions/github-script@0.9.0
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['tests-passed']
          })
