version: 2
jobs:
  macos-build:
    macos:
      xcode: "9.3.1"

    steps:
    - run: brew install pyenv readline xz

    - run: |-
        # https://circleci.com/docs/2.0/env-vars/#interpolating-environment-variables-to-set-other-environment-variables
        echo '
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
        ' >> $BASH_ENV

    - run: |-
        for py_ver in 3.7.0 3.6.4 3.5.4 pypy3.5-6.0.0
        do
          pyenv install "$py_ver" &
        done
        wait
    - run: pyenv global 3.7.0 3.6.4 3.5.4 pypy3.5-6.0.0

    - run: pip install tox tox-pyenv
    - checkout
    - run: tox -e py35,py36,py37,pypy3 -- -p no:sugar
    - store_test_results:
        path: .test-results
    - store_artifacts:
        path: .test-results

  linux-build:
    docker:
    - image: randomknowledge/docker-pyenv-tox

    steps:
    - checkout
    - run: pip install tox
    - run: tox -e py35,py36,py37
    - store_test_results:
        path: .test-results
    - store_artifacts:
        path: .test-results

workflows:
  version: 2
  test-linux-and-macos:
    jobs:
    - macos-build
    - linux-build
