# coding: utf-8

"""
    KF Pipelines API

    Generated python client for the KF Pipelines server API  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import kfp_server_api
from kfp_server_api.models.api_read_artifact_response import ApiReadArtifactResponse  # noqa: E501
from kfp_server_api.rest import ApiException


class TestApiReadArtifactResponse(unittest.TestCase):
    """ApiReadArtifactResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiReadArtifactResponse(self):
        """Test ApiReadArtifactResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kfp_server_api.models.api_read_artifact_response.ApiReadArtifactResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
