[tool.poetry]
name = "loopr"
version = "0.1"
description = "Loopr python client"
authors = ["Subhankar"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
