[tool.poetry]
name = "objecttracer"
version = "1.1.0"
description = "Small utility to log the activity on a given object."
authors = ["Sylvain Roy <sylvain.roy@m4x.org>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
