[tool.poetry]
name = "aiogram-cli"
version = "0.0.1-alpha.0"
description = ""
authors = ["Alex Root Junior <jroot.junior@gmail.com>"]
license = "MIT"
classifiers = [
	"Development Status :: 1 - Planning",
	"Environment :: Console",
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
