# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spaceone/api/statistics/v1/stat.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from spaceone.api.core.v1 import query_pb2 as spaceone_dot_api_dot_core_dot_v1_dot_query__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='spaceone/api/statistics/v1/stat.proto',
  package='spaceone.api.statistics.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n%spaceone/api/statistics/v1/stat.proto\x12\x1aspaceone.api.statistics.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1cgoogle/api/annotations.proto\x1a spaceone/api/core/v1/query.proto\"}\n\tJoinQuery\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x16\n\x0e\x64\x61ta_source_id\x18\x02 \x01(\t\x12\x15\n\rresource_type\x18\x03 \x01(\t\x12\x34\n\x05query\x18\x04 \x01(\x0b\x32%.spaceone.api.core.v1.StatisticsQuery\"(\n\x07\x46ormula\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x66ormula\x18\x02 \x01(\t\"\xf6\x01\n\x10QueryStatRequest\x12\x16\n\x0e\x64\x61ta_source_id\x18\x01 \x01(\t\x12\x15\n\rresource_type\x18\x02 \x01(\t\x12\x34\n\x05query\x18\x03 \x01(\x0b\x32%.spaceone.api.core.v1.StatisticsQuery\x12\x33\n\x04join\x18\x04 \x03(\x0b\x32%.spaceone.api.statistics.v1.JoinQuery\x12\x35\n\x08\x66ormulas\x18\x05 \x03(\x0b\x32#.spaceone.api.statistics.v1.Formula\x12\x11\n\tdomain_id\x18\x06 \x01(\t\"J\n\x08StatInfo\x12+\n\x07results\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.ListValue\x12\x11\n\tdomain_id\x18\x02 \x01(\t2\x86\x01\n\x04Stat\x12~\n\x05query\x12,.spaceone.api.statistics.v1.QueryStatRequest\x1a$.spaceone.api.statistics.v1.StatInfo\"!\x82\xd3\xe4\x93\x02\x1b\"\x19/statistics/v1/stat/queryb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,spaceone_dot_api_dot_core_dot_v1_dot_query__pb2.DESCRIPTOR,])




_JOINQUERY = _descriptor.Descriptor(
  name='JoinQuery',
  full_name='spaceone.api.statistics.v1.JoinQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='spaceone.api.statistics.v1.JoinQuery.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_source_id', full_name='spaceone.api.statistics.v1.JoinQuery.data_source_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resource_type', full_name='spaceone.api.statistics.v1.JoinQuery.resource_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='query', full_name='spaceone.api.statistics.v1.JoinQuery.query', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=288,
)


_FORMULA = _descriptor.Descriptor(
  name='Formula',
  full_name='spaceone.api.statistics.v1.Formula',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='spaceone.api.statistics.v1.Formula.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='formula', full_name='spaceone.api.statistics.v1.Formula.formula', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=330,
)


_QUERYSTATREQUEST = _descriptor.Descriptor(
  name='QueryStatRequest',
  full_name='spaceone.api.statistics.v1.QueryStatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_source_id', full_name='spaceone.api.statistics.v1.QueryStatRequest.data_source_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resource_type', full_name='spaceone.api.statistics.v1.QueryStatRequest.resource_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='query', full_name='spaceone.api.statistics.v1.QueryStatRequest.query', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='join', full_name='spaceone.api.statistics.v1.QueryStatRequest.join', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='formulas', full_name='spaceone.api.statistics.v1.QueryStatRequest.formulas', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domain_id', full_name='spaceone.api.statistics.v1.QueryStatRequest.domain_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=579,
)


_STATINFO = _descriptor.Descriptor(
  name='StatInfo',
  full_name='spaceone.api.statistics.v1.StatInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='spaceone.api.statistics.v1.StatInfo.results', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domain_id', full_name='spaceone.api.statistics.v1.StatInfo.domain_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=581,
  serialized_end=655,
)

_JOINQUERY.fields_by_name['query'].message_type = spaceone_dot_api_dot_core_dot_v1_dot_query__pb2._STATISTICSQUERY
_QUERYSTATREQUEST.fields_by_name['query'].message_type = spaceone_dot_api_dot_core_dot_v1_dot_query__pb2._STATISTICSQUERY
_QUERYSTATREQUEST.fields_by_name['join'].message_type = _JOINQUERY
_QUERYSTATREQUEST.fields_by_name['formulas'].message_type = _FORMULA
_STATINFO.fields_by_name['results'].message_type = google_dot_protobuf_dot_struct__pb2._LISTVALUE
DESCRIPTOR.message_types_by_name['JoinQuery'] = _JOINQUERY
DESCRIPTOR.message_types_by_name['Formula'] = _FORMULA
DESCRIPTOR.message_types_by_name['QueryStatRequest'] = _QUERYSTATREQUEST
DESCRIPTOR.message_types_by_name['StatInfo'] = _STATINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JoinQuery = _reflection.GeneratedProtocolMessageType('JoinQuery', (_message.Message,), {
  'DESCRIPTOR' : _JOINQUERY,
  '__module__' : 'spaceone.api.statistics.v1.stat_pb2'
  # @@protoc_insertion_point(class_scope:spaceone.api.statistics.v1.JoinQuery)
  })
_sym_db.RegisterMessage(JoinQuery)

Formula = _reflection.GeneratedProtocolMessageType('Formula', (_message.Message,), {
  'DESCRIPTOR' : _FORMULA,
  '__module__' : 'spaceone.api.statistics.v1.stat_pb2'
  # @@protoc_insertion_point(class_scope:spaceone.api.statistics.v1.Formula)
  })
_sym_db.RegisterMessage(Formula)

QueryStatRequest = _reflection.GeneratedProtocolMessageType('QueryStatRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYSTATREQUEST,
  '__module__' : 'spaceone.api.statistics.v1.stat_pb2'
  # @@protoc_insertion_point(class_scope:spaceone.api.statistics.v1.QueryStatRequest)
  })
_sym_db.RegisterMessage(QueryStatRequest)

StatInfo = _reflection.GeneratedProtocolMessageType('StatInfo', (_message.Message,), {
  'DESCRIPTOR' : _STATINFO,
  '__module__' : 'spaceone.api.statistics.v1.stat_pb2'
  # @@protoc_insertion_point(class_scope:spaceone.api.statistics.v1.StatInfo)
  })
_sym_db.RegisterMessage(StatInfo)



_STAT = _descriptor.ServiceDescriptor(
  name='Stat',
  full_name='spaceone.api.statistics.v1.Stat',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=658,
  serialized_end=792,
  methods=[
  _descriptor.MethodDescriptor(
    name='query',
    full_name='spaceone.api.statistics.v1.Stat.query',
    index=0,
    containing_service=None,
    input_type=_QUERYSTATREQUEST,
    output_type=_STATINFO,
    serialized_options=b'\202\323\344\223\002\033\"\031/statistics/v1/stat/query',
  ),
])
_sym_db.RegisterServiceDescriptor(_STAT)

DESCRIPTOR.services_by_name['Stat'] = _STAT

# @@protoc_insertion_point(module_scope)
