
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-22T14:55:47+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "85d557d51e311d7d83ef43c808267387db00c7b1",
 "version": "1.8.0.post.dev34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
