[tool.poetry]
name = "flake8-flask"
version = "0.9.3"
readme = "README.md"
description = "Static analysis checks for Flask, by r2c. Available in our free program analysis tool, Bento. (ht"
authors = ["grayson <grayson@returntocorp.com>"]
classifiers=[
  "Programming Language :: Python :: 3",
  "License :: Other/Proprietary License",
  "Operating System :: OS Independent",
]
packages = [
  { include = "flake8_flask"},
]
exclude = ["tests/**"]

[tool.poetry.dependencies]
python = "^3.6"
flake8 = "^3.7.9"
r2c-py-ast = "0.1.0b1"

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"
pytest-cov = "^2.8.1"
pre-commit = "^1.21.0"

[tool.poetry.plugins]
[tool.poetry.plugins."flake8.extension"]
r2c-flake8 = "flake8_flask.main:Flake8Flask"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
