includes:
- ./defaults.yaml

dataset_config:
  visual_entailment:
    return_info: true
    image_features:
        train:
        - datasets/visual_entailment/features/lmdbs/flickr30k.lmdb
        - datasets/visual_entailment/features/lmdbs/flickr30k.lmdb
        val:
        - datasets/visual_entailment/features/lmdbs/flickr30k.lmdb
        test:
        - datasets/visual_entailment/features/lmdbs/flickr30k.lmdb
    imdb_files:
        train:
        - datasets/visual_entailment/imdbs/snli_ve_train.jsonl
        - datasets/visual_entailment/imdbs/snli_ve_dev.jsonl
        val:
        - datasets/visual_entailment/imdbs/snli_ve_test.jsonl
        test:
        - datasets/visual_entailment/imdbs/snli_ve_test.jsonl
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128
