#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['fakepkg']

package_data = \
{'': ['*']}

entry_points = \
{'console_scripts': ['fakepkg = fakepkg:main']}

setup(name='fakepkg',
      version='0.1.0',
      description='This is my great package!',
      author='Brendan Abel',
      author_email='007brendan@gmail.com',
      url='http://github.com/bpabel',
      packages=packages,
      package_data=package_data,
      entry_points=entry_points,
     )
