# Connect Box IP address
ip_address: 192.168.0.1

# Connect Box web interface password
password: WhatEverYourPasswordIs

# The following parameters are optional:
#exporter:
  # port on which this exporter exposes metrics (default: 9705)
  #port: 9705

  # timeout duration for connections to the Connect Box (default: 9)
  #timeout_seconds: 9