[tool.poetry]
name = "cognite-databricks-utils"
version = "0.0.1"
description = "Utilities for administrating a Databricks shard"
authors = ["Magnus Moan <magnus.moan@cognite.com>"]

packages = [
    { include="cognite", from="." },
]

[tool.black]
line-length = 120
target_version = ['py37']
include = '\.py$'

[tool.isort]
line_length=120                # corresponds to -w  flag
multi_line_output=3            # corresponds to -m  flag
include_trailing_comma=true    # corresponds to -tc flag
skip_glob = '^((?!py$).)*$'    # this makes sort all Python files
known_third_party = ["click", "databricks_api", "pytest", "requests", "xlrd"]

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
envlist = py37,py38

[testenv]
deps =
    pytest
    pytest-cov

commands =
    coverage run --source cognite -m pytest -v tests
    coverage xml
"""

[tool.poetry.scripts]
db-util = 'cognite.databricks_utils.cli:run'

[tool.poetry.dependencies]
python = "^3.7"
databricks-api = "^0.4.0"
xlrd = "^1.2.0"
click = "^7.1.1"
python-semantic-release = "^6.0.1"

[tool.poetry.dev-dependencies]
isort = "^4.3.21"
pre-commit = "^2.2.0"
pytest = "^5.4.1"
pytest-cov = "^2.8.1"
black = "^19.10b0"
mypy = "^0.770"
flake8 = "^3.7.9"
tox = "^3.14.6"
tox-pyenv = "^1.1.0"


[[tool.poetry.source]]
name = "snakepit"
url = "https://cognite.jfrog.io/cognite/api/pypi/snakepit/simple"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
