[tool.poetry]
name = "open-link"
version = "0.1.1"
description = ""
authors = ["Eyal Levin <eyalev@gmail.com>"]

[tool.poetry.scripts]
open-link = "open_link.main:main"

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.1"
pyperclip = "^1.8.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
