[tool.poetry]
name = "env-credentials"
version = "0.1.0"
description = "A library to maintain and use encrypted .env files."
license = "MIT"
authors = ["Chris Muthig <camuthig@gmail.com>"]
readme = 'README.md'
repository = 'https://github.com/camuthig/python-env-credentials'
documentation = 'https://github.com/camuthig/python-env-credentials'
keywords = [
    "dotenv",
    "credentials",
    "encrypted",
    "settings",
    "environment variables",
    "env",
]
packages = [
    { include = "env_credentials" },
    { include = "django_credentials" }
]

[tool.poetry.dependencies]
python = "^3.6"
cryptography = "^2.9"
python-dotenv = "^0.13.0"
django = {version = "^3.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.770"
django-stubs = "^1.5.0"
flake8 = "^3.7.9"

[tool.poetry.extras]

django = ["django"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
