[tool.poetry]
name = "koverj"
version = "0.1.104"
description = "Test coverage for selenium based tests"
authors = ["Ivan Huryn <igur007@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Igur007/koverj-py"

[tool.poetry.dependencies]
python = "^3.7"
selene = "^1.0.0a13"
requests = "^2.23.0"
future = "^0.18.2"
selenium = "3.141"
configparser = "^5.0.0"
pytest = "*"
uplink = "^0.9.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
