[tool.poetry]
name = "yinasrun"
version = "1.0.0"
description = ""
authors = ["italian roast"]

[tool.poetry.dependencies]
python = "^3.7"
fire = "^0.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
yin = 'yinasrun:run'
