[tool.poetry]
name = "dyndb"
version = "0.1.1"
description = ""
authors = ["Pascal Prins <pascal.prins@foobar-it.com>"]

[tool.poetry.dependencies]
python = "^2.7 || ^3.7"
click = "^7.1.1"
boto3 = "^1.12.26"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
dyndb = "dyndb.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

