[tool.poetry]
name = "ac-app-installer"
version = "0.3.0"
description = ""
authors = ["Steven Kling <steven.kling@appfire.com>"]
packages = [
    { include = "ac_app_installer" },
    { include = "ac_app_deploy" },
]

[tool.poetry.scripts]
createAppfireApp = 'ac_app_installer.install:process'
deployAppfireApp = 'ac_app_deploy.deploy:process'

[tool.poetry.dependencies]
python = "^3.7"
funcy = "^1.14"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
