[tool.poetry]
name = "oneservice"
version = "0.1.0"
description = ""
license = "MIT"
authors = ["Davide Vitelaru <davide@vitelaru.com>"]
readme = "README.md"
keywords = ["microservice", "micro", "service", "oneservice", "one"]
repository = "https://gitlab.com/davidevi/oneservice"

[tool.poetry.dependencies]
python = "^3.7"
flask = "^1.1.2"

[tool.poetry.dev-dependencies]
invoke = "^1.4.1"
pytest-cov = "^2.8.1"
pytest = "^5.2"
black = "^19.10b0"
flake8 = "^3.7.9"
mypy = "^0.770"

[tool.poetry.scripts]
mypy = "tasks:mypy"
flake8 = "tasks:flake8"
check = "tasks:check"
test = "tasks:test"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


