apiVersion: v1
kind: Service
metadata:
  name: kubesync-example-service
  labels:
    app: kubesync-example
spec:
  selector:
    app: kubesync-example
  type: LoadBalancer
  ports:
    - port: 8011
      targetPort: 80
      name: kubesync-example-port

---

apiVersion: v1
kind: Pod
metadata:
  name: kubesync-example-pod
  labels:
    app: kubesync-example
spec:
  containers:
    - name: nginx
      image: kubesync-nginx:latest
      imagePullPolicy: IfNotPresent
      readinessProbe:
        httpGet:
          port: 80
          path: /
