__version__ = '0.0.1'
__title__ = 'zwpool'
__description__ = 'Personal Pool utils.'
__url__ = 'https://github.com/njzhaowei/zwpool'
__author__ = 'Zhao Wei'
__author_email__ = 'yewberry@163.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2020 Zhao Wei'