
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-21T10:54:01+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "416dd9c185a72fcb6a5cd0410ab7028dcd35e497",
 "version": "0.3.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
