[tool.poetry]
name = "recipebook"
version = "0.1.0"
description = "I'm writing a cookbook to learn Python, Postgresql, and other potential tools."
authors = ["Mike Martino <mikemartino86@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
