[tool.poetry]
name = "iso18245"
version = "1.0.0"
description = "ISO 18245 Merchant Category Codes database"
authors = ["Jerome Leclanche <jerome@leclan.ch>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
use-tabs = true
