[tool.poetry]
name = "v6gen"
version = "0.1.0"
description = "Simple tool for generating IPv6 addresses randomly or based by the hostname"
authors = ["Michael Vieira <contact@mvieira.fr>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^19.10b0"

[tool.black]
line-length = 79
skip-string-normalization = false
include = '\.py$'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
