[build-system]
requires = [
    "setuptools",
    "setuptools_scm",
    "six",
    "pytest-runner",
    "pytest-harvest",
    "wheel",
    "wrapt",
    "pandas",
    "tabulate",
]
build-backend = "setuptools.build_meta"
