[tool.poetry]
name = "darwin_handlers"
version = "0.1.2"
description = ""
authors = ["Kevin Hill <kivo360@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.6.0"
jamboree = "0.7.2"
pandas_datareader = "^0.8.1"
skorch = "^0.8.0"
dask = "^2.14.0"
matplotlib = "^3.2.1"

faker = "^4.0.3"
maya = "^0.6.1"

[tool.poetry.dev-dependencies]
yapf = "^0.29.0"
jupyter = "^1.0.0"
pylint = "^2.4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
