mappings:
  - display_name: Doulos
    in_lang: hei-doulos
    out_lang: hei
    authors:
      - Aidan Pine
    mapping: hei_doulos.csv
    language_name: Heiltsuk
  - display_name: Times
    in_lang: hei-times-font
    out_lang: hei
    authors:
      - Aidan Pine
    mapping: hei_times.csv
    language_name: Heiltsuk
  - display_name: Times
    mapping: nav_times.csv
    in_lang: nav-times-font
    out_lang: nav
    language_name: Navajo
    authors:
      - Aidan Pine
  - display_name: First Nations Unicode
    mapping: fv_unicode.csv
    in_lang: fv-unicode-font
    out_lang: fv-unicode
    norm_form: NFD
    escape_special: true
    case_sensitive: false
    language_name: Undetermined
    authors:
      - Aidan Pine