#https://flit.readthedocs.io/en/latest/pyproject_toml.html
[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "wtypes"
author = "deathbeds"
author-email = "tony.fast@gmail.com"
requires = ["jsonschema", "munch", "anyconfig", "pluggy"]
keywords = ""
home-page = "https://github.com/deathbeds/wtypes"
license = "BSD-3-Clause"
description-file = "README.md"


[tool.flit.metadata.requires-extra]
examples = ["hypothesis-jsonschema", "genson"]
widgets = ["param", "ipywidgets"]
[tool.flit.metadata.urls]    
[tool.flit.scripts]
[tool.flit.sdist]

[tool.coverage.run]
[tool.coverage.report]
[tool.coverage.html]
