os: linux
language: python

matrix:
  include:
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
  - language: c
    arch: arm64
  - language: c
    arch: ppc64le
  - language: c
    arch: s390x
  - python: "3.7"
    env: LINTER=1

sudo: required
services:
  - docker

notifications:
  email: false

before_install:
  - if [ "$(uname -m)" != "x86_64" ]; then sudo apt-get install -y python3-pip python3-venv && python3 -m venv ./.venv && source ./.venv/bin/activate; fi
  - pip install --upgrade pip setuptools

install:
  - pip install -r test-requirements.txt
  - pip install tox codecov
  - pip install -e .

script:
  - tests/travis.sh

cache:
  directories:
    - $HOME/.cache/auditwheel_tests
