imports:
  - '@databricksbundle/spark/spark_autodetect.yaml'

parameters:
  databricksbundle:
    databricksConnect:
      connection:
        address: 'https://dbc-123.cloud.databricks.com'
        token: ''
        clusterId: ''
