[tool.poetry]
name = "resquare"
version = "0.0.1"
description = "Utility for expanding the frame size of a logo image while preserving the background color of the original image."
authors = ["faizanbhat <faizan.bhat@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.4"
Pillow = "^7.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"