
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-25T18:19:41+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9bcf3242f814c71168d36ad3aafab6a0867e1c3a",
 "version": "0.0.43"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
