# Configuration for Plot Twist Project

# Defines Artella project ID number
id_number: "9"

# Defines the Artella Project ID
id: "973a70a7-1494-422b-b8c1-696587030e59"

# Defines the URL of the project
url: "http://www.plottwist-film.com/"

# Defines the list of emails to notify when a tool is broken
emails:
  - tpovedatd@gmail.com

# Defines the URL where project tools documentations is located
documentation_url: "https://plot-twist-short-film.github.io/plottwist-docs/pipeline/"

extensions:
  - ma
  - abc

default_extension: ma

# Defines list of departments
departments:
  - Modeling
  - Shading
  - FX
  - Lighting
  - Compo
  - Grooming
  - Rigging
  - Layout

# Define configuration variables for project progress bar
progress_bar:
  color0: "58, 92, 84"
  color1: "213, 173, 0"

# Defines available libs
libs:
  - artella
  - naming
  - kitsu
  - pyblish
  - alembic
  - usd

# Defines available tools
tools:
  - changelog
  - bugtracker
  - artellamanager
  - artellauploader
  - assetsmanager
  - shadersmanager
  - lightrigsmanager
  - assetslibrary
  - namemanager
  - modelchecker
  - dependenciesmanager
  - renamer
  - customtool