language: python

os:
  - linux

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - python setup.py develop

script:
  - nosetests --with-doctest triangle/tri.py

notifications:
  email: false
