dataset_config:
  vizwiz:
    return_info: true
    image_features:
      train:
      - datasets/vizwiz/features/lmdbs/vizwiz.lmdb
      - datasets/vizwiz/features/lmdbs/vizwiz.lmdb
      val:
      - datasets/vizwiz/features/lmdbs/vizwiz.lmdb
      test:
      - datasets/vizwiz/features/lmdbs/vizwiz.lmdb
    imdb_files:
      train:
      - datasets/vizwiz/imdbs/imdb_vizwiz_train.npy
      - datasets/vizwiz/imdbs/imdb_vizwiz_val.npy
    processors:
      # Stop fasttext from loading by overriding the context_processor
      context_processor:
        type: simple_word
        params: {}
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128
