#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pyship']

package_data = \
{'': ['*']}

install_requires = \
['attrs',
 'balsa',
 'pyinstaller',
 'sundry',
 'typeguard',
 'requests',
 'semver',
 'toml',
 'ismain']

setup(name='pyship',
      version='0.0.2',
      description='pyship - ship python apps ',
      author='James Abel',
      author_email='j@abel.co',
      url='https://github.com/jamesabel/pyship',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
     )
