########## SENSITIVE SECTION WARNING ###########
################################################
# Any edits of any of the exported names       #
# may result in a breaking change.             #
# Ensure no names are removed without warning. #
################################################

### DEP-WARN: Check this *every* discord.py update
from discord.ext.commands import ArgumentParsingError as ArgumentParsingError
from discord.ext.commands import AutoShardedBot as AutoShardedBot
from discord.ext.commands import BadArgument as BadArgument
from discord.ext.commands import BadUnionArgument as BadUnionArgument
from discord.ext.commands import Bot as Bot
from discord.ext.commands import BotMissingAnyRole as BotMissingAnyRole
from discord.ext.commands import BotMissingRole as BotMissingRole
from discord.ext.commands import BucketType as BucketType
from discord.ext.commands import CategoryChannelConverter as CategoryChannelConverter
from discord.ext.commands import CheckAnyFailure as CheckAnyFailure
from discord.ext.commands import CheckFailure as CheckFailure
from discord.ext.commands import CogMeta as CogMeta
from discord.ext.commands import ColourConverter as ColourConverter
from discord.ext.commands import CommandError as CommandError
from discord.ext.commands import CommandInvokeError as CommandInvokeError
from discord.ext.commands import CommandNotFound as CommandNotFound
from discord.ext.commands import CommandOnCooldown as CommandOnCooldown
from discord.ext.commands import ConversionError as ConversionError
from discord.ext.commands import Converter as Converter
from discord.ext.commands import Cooldown as Cooldown
from discord.ext.commands import CooldownMapping as CooldownMapping
from discord.ext.commands import DefaultHelpCommand as DefaultHelpCommand
from discord.ext.commands import DisabledCommand as DisabledCommand
from discord.ext.commands import EmojiConverter as EmojiConverter
from discord.ext.commands import ExpectedClosingQuoteError as ExpectedClosingQuoteError
from discord.ext.commands import ExtensionAlreadyLoaded as ExtensionAlreadyLoaded
from discord.ext.commands import ExtensionError as ExtensionError
from discord.ext.commands import ExtensionFailed as ExtensionFailed
from discord.ext.commands import ExtensionNotFound as ExtensionNotFound
from discord.ext.commands import ExtensionNotLoaded as ExtensionNotLoaded
from discord.ext.commands import GameConverter as GameConverter
from discord.ext.commands import Greedy as Greedy
from discord.ext.commands import HelpCommand as HelpCommand
from discord.ext.commands import IDConverter as IDConverter
from discord.ext.commands import InvalidEndOfQuotedStringError as InvalidEndOfQuotedStringError
from discord.ext.commands import InviteConverter as InviteConverter
from discord.ext.commands import MaxConcurrency as MaxConcurrency
from discord.ext.commands import MaxConcurrencyReached as MaxConcurrencyReached
from discord.ext.commands import MemberConverter as MemberConverter
from discord.ext.commands import MessageConverter as MessageConverter
from discord.ext.commands import MinimalHelpCommand as MinimalHelpCommand
from discord.ext.commands import MissingAnyRole as MissingAnyRole
from discord.ext.commands import MissingPermissions as MissingPermissions
from discord.ext.commands import MissingRequiredArgument as MissingRequiredArgument
from discord.ext.commands import MissingRole as MissingRole
from discord.ext.commands import NoEntryPointError as NoEntryPointError
from discord.ext.commands import NoPrivateMessage as NoPrivateMessage
from discord.ext.commands import NotOwner as NotOwner
from discord.ext.commands import NSFWChannelRequired as NSFWChannelRequired
from discord.ext.commands import Paginator as Paginator
from discord.ext.commands import PartialEmojiConverter as PartialEmojiConverter
from discord.ext.commands import PrivateMessageOnly as PrivateMessageOnly
from discord.ext.commands import RoleConverter as RoleConverter
from discord.ext.commands import TextChannelConverter as TextChannelConverter
from discord.ext.commands import TooManyArguments as TooManyArguments
from discord.ext.commands import UnexpectedQuoteError as UnexpectedQuoteError
from discord.ext.commands import UserConverter as UserConverter
from discord.ext.commands import UserInputError as UserInputError
from discord.ext.commands import VoiceChannelConverter as VoiceChannelConverter
from discord.ext.commands import bot_has_guild_permissions as bot_has_guild_permissions
from discord.ext.commands import check_any as check_any
from discord.ext.commands import clean_content as clean_content
from discord.ext.commands import max_concurrency as max_concurrency

from ._dpy_reimplements import bot_has_any_role as bot_has_any_role
from ._dpy_reimplements import bot_has_role as bot_has_role
from ._dpy_reimplements import check as check
from ._dpy_reimplements import cooldown as cooldown
from ._dpy_reimplements import dm_only as dm_only
from ._dpy_reimplements import guild_only as guild_only
from ._dpy_reimplements import has_any_role as has_any_role
from ._dpy_reimplements import has_role as has_role
from ._dpy_reimplements import is_nsfw as is_nsfw
from ._dpy_reimplements import when_mentioned as when_mentioned
from ._dpy_reimplements import when_mentioned_or as when_mentioned_or
from .commands import RESERVED_COMMAND_NAMES as RESERVED_COMMAND_NAMES
from .commands import Cog as Cog
from .commands import CogCommandMixin as CogCommandMixin
from .commands import CogGroupMixin as CogGroupMixin
from .commands import CogMixin as CogMixin
from .commands import Command as Command
from .commands import Group as Group
from .commands import GroupMixin as GroupMixin
from .commands import command as command
from .commands import group as group
from .context import Context as Context
from .context import DMContext as DMContext
from .context import GuildContext as GuildContext
from .converter import APIToken as APIToken
from .converter import DictConverter as DictConverter
from .converter import GuildConverter as GuildConverter
from .converter import Literal as Literal
from .converter import NoParseOptional as NoParseOptional
from .converter import TimedeltaConverter as TimedeltaConverter
from .converter import UserInputOptional as UserInputOptional
from .converter import get_dict_converter as get_dict_converter
from .converter import get_timedelta_converter as get_timedelta_converter
from .converter import parse_timedelta as parse_timedelta
from .errors import ArgParserFailure as ArgParserFailure
from .errors import BotMissingPermissions as BotMissingPermissions
from .errors import ConversionFailure as ConversionFailure
from .errors import UserFeedbackCheckFailure as UserFeedbackCheckFailure
from .help import HelpSettings as HelpSettings
from .help import KronHelpFormatter as KronHelpFormatter
from .help import kron_help as kron_help
from .requires import DM_PERMS as DM_PERMS
from .requires import CheckPredicate as CheckPredicate
from .requires import GlobalPermissionModel as GlobalPermissionModel
from .requires import GuildPermissionModel as GuildPermissionModel
from .requires import PermissionModel as PermissionModel
from .requires import PermState as PermState
from .requires import PrivilegeLevel as PrivilegeLevel
from .requires import Requires as Requires
from .requires import admin as admin
from .requires import admin_or_permissions as admin_or_permissions
from .requires import bot_has_permissions as bot_has_permissions
from .requires import guildowner as guildowner
from .requires import guildowner_or_permissions as guildowner_or_permissions
from .requires import has_guild_permissions as has_guild_permissions
from .requires import has_permissions as has_permissions
from .requires import is_owner as is_owner
from .requires import mod as mod
from .requires import mod_or_permissions as mod_or_permissions
from .requires import permissions_check as permissions_check
