# coding: utf-8

"""
    defektor Controll API

    defektor controll aplication interface  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sob@dei.uc.pt
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from defektor_api.configuration import Configuration


class Ijk(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'target_types': 'list[TargetType]'
    }

    attribute_map = {
        'name': 'name',
        'target_types': 'targetTypes'
    }

    def __init__(self, name=None, target_types=None, local_vars_configuration=None):  # noqa: E501
        """Ijk - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._target_types = None
        self.discriminator = None

        self.name = name
        self.target_types = target_types

    @property
    def name(self):
        """Gets the name of this Ijk.  # noqa: E501


        :return: The name of this Ijk.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Ijk.


        :param name: The name of this Ijk.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def target_types(self):
        """Gets the target_types of this Ijk.  # noqa: E501


        :return: The target_types of this Ijk.  # noqa: E501
        :rtype: list[TargetType]
        """
        return self._target_types

    @target_types.setter
    def target_types(self, target_types):
        """Sets the target_types of this Ijk.


        :param target_types: The target_types of this Ijk.  # noqa: E501
        :type: list[TargetType]
        """
        if self.local_vars_configuration.client_side_validation and target_types is None:  # noqa: E501
            raise ValueError("Invalid value for `target_types`, must not be `None`")  # noqa: E501

        self._target_types = target_types

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Ijk):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Ijk):
            return True

        return self.to_dict() != other.to_dict()
