[tool.poetry]
name = "spamdetector"
version = "0.1.1"
description = "Spam Classifier/Detector ML Package"
authors = ["Rohit Kumar <rohit1998kg@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
joblib = "^0.14.1"
scikit-learn = "^0.22.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
