# coding: utf-8

"""
    Jordskredvarsel API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import varsom_landslide_client
from models.media_type_header_value import MediaTypeHeaderValue  # noqa: E501
from varsom_landslide_client.rest import ApiException


class TestMediaTypeHeaderValue(unittest.TestCase):
    """MediaTypeHeaderValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMediaTypeHeaderValue(self):
        """Test MediaTypeHeaderValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = varsom_landslide_client.models.media_type_header_value.MediaTypeHeaderValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
