dataset_config:
  masked_coco:
    return_info: true
    image_features:
      train:
      - datasets/coco/features/lmdbs/coco_trainval2014.lmdb
      - datasets/coco/features/lmdbs/coco_trainval2014.lmdb
    imdb_files:
      train:
      - datasets/coco/imdbs/imdb_karpathy_train_by_image.npy
      - datasets/coco/imdbs/imdb_karpathy_val_by_image.npy
