[tool.poetry]
name = "pytchout"
version = "0.1.0"
description = "A package for downloading baseball data and performing baseball data analytics in Python."
authors = ["Josh Hejka <josh@joshhejka.com>"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.18.2"
pandas = "^1.0.3"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.7.9"
invoke = "^1.4.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
