# thanks a lot to the Nansat project (https://github.com/nansencenter/nansat) from which this file was adapted
environment:
  matrix:
    - TARGET_ARCH: x64
      CONDA_PY: 36
      CONDA_INSTALL_LOCN: C:\Miniconda36-x64
      GDAL_DATA: C:\Miniconda36-x64\Library\share\gdal
      PROJECT_DIR: C:\projects\spatialist

platform:
    - x64

install:
    # Cygwin's git breaks conda-build. (See https://github.com/conda-forge/conda-smithy-feedstock/pull/2.)
    - rmdir C:\cygwin /s /q

    # activate conda
    - call %CONDA_INSTALL_LOCN%\Scripts\activate.bat

    # If there is a newer build queued for the same PR, cancel this one.
    - appveyor DownloadFile https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py
    - python ff_ci_pr_build.py -v --ci "appveyor" "%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_SLUG%" "%APPVEYOR_BUILD_NUMBER%" "%APPVEYOR_PULL_REQUEST_NUMBER%"
    - del ff_ci_pr_build.py

    # update conda
    - conda update --yes --quiet conda

    - set PYTHONUNBUFFERED=1

    # Add our channels.
    - conda config --set show_channel_urls true
    - conda config --remove channels defaults
    - conda config --add channels defaults
    - conda config --add channels conda-forge

    # Configure the VM.
    - conda install -n root --quiet --yes gdal swig
    - python -m pip install --upgrade pip
    - python -m pip install -r requirements-dev.txt coveralls coverage
    - python setup.py install

# Skip .NET project specific build phase.
build: off

test_script:
    - coverage run --source spatialist/ -m pytest

#after_test:
#  - coveralls
