channels:
  - conda-forge
  - defaults
dependencies:
  - progressbar2
  - pathos>=0.2
  - numpy
  - matplotlib
  - jupyter
  - IPython
  - ipywidgets
  - tblib
  - pyyaml
  - gdal
  - pip
  - pip:
      - scoop
