
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-23T09:12:43-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d8eda6d497807e55a10d954e7ed3d04b4239c41a",
 "version": "v1.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
