[tool.poetry]
name = "ticker-to-searchable-terms"
version = "0.010"
description = "This is used to generate searchable terms for companies listed on NASDAQ NYSE. Includes"
license = "MIT"
authors = ["Henry Becket Trotter <beckettrotter@gmail.com>"]
readme = "README.txt"
homepage = "https://github.com/BecketTrotter/ticker_to_searchable_terms"
repository = "https://github.com/BecketTrotter/ticker_to_searchable_terms"
keywords = ['stock', 'ticker', 'ceo', 'executives', 'seo']
include = [
    "LICENSE",
]
classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"