[tool.poetry]
name = "xlwombat"
version = "0.1.0"
description = ""
authors = ["wiliam chu <chudood@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
jinja2 = "^2.11.2"
openpyxl = "^3.0.3"

[tool.poetry.dev-dependencies]
pydantic = "^1.4"
isort = "^4.3.21"
black = "^19.10b0"
requests = "^2.23.0"
mypy = "^0.770"
coverage = "^5.1"
pytest-cov = "^2.8.1"
ipython = "^7.13.0"
pylint = "^2.4.4"
pdbpp = "^0.10.2"
rope = "^0.16.0"
pytest = "^5.4.1"

[tool.isort]
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
line_length=88


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[mypy]
strict_optional = true
warn_redundant_casts = true
follow_imports = "skip"
warn_no_return = true
ignore_missing_imports = true

