# coding: utf-8

"""
    API Manager API v1.3

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3.0
    Contact: support@axway.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class APIAccess(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'api_id': 'str',
        'created_by': 'str',
        'state': 'str',
        'created_on': 'int',
        'enabled': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'api_id': 'apiId',
        'created_by': 'createdBy',
        'state': 'state',
        'created_on': 'createdOn',
        'enabled': 'enabled'
    }

    def __init__(self, id=None, api_id=None, created_by=None, state=None, created_on=None, enabled=False):  # noqa: E501
        """APIAccess - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._api_id = None
        self._created_by = None
        self._state = None
        self._created_on = None
        self._enabled = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if api_id is not None:
            self.api_id = api_id
        if created_by is not None:
            self.created_by = created_by
        if state is not None:
            self.state = state
        if created_on is not None:
            self.created_on = created_on
        if enabled is not None:
            self.enabled = enabled

    @property
    def id(self):
        """Gets the id of this APIAccess.  # noqa: E501

        Unique identifier for approval decisions (includes pending approvals)  # noqa: E501

        :return: The id of this APIAccess.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this APIAccess.

        Unique identifier for approval decisions (includes pending approvals)  # noqa: E501

        :param id: The id of this APIAccess.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def api_id(self):
        """Gets the api_id of this APIAccess.  # noqa: E501

        Virtualised REST API unique id  # noqa: E501

        :return: The api_id of this APIAccess.  # noqa: E501
        :rtype: str
        """
        return self._api_id

    @api_id.setter
    def api_id(self, api_id):
        """Sets the api_id of this APIAccess.

        Virtualised REST API unique id  # noqa: E501

        :param api_id: The api_id of this APIAccess.  # noqa: E501
        :type: str
        """

        self._api_id = api_id

    @property
    def created_by(self):
        """Gets the created_by of this APIAccess.  # noqa: E501

        The unique identifier for user that requested access  # noqa: E501

        :return: The created_by of this APIAccess.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this APIAccess.

        The unique identifier for user that requested access  # noqa: E501

        :param created_by: The created_by of this APIAccess.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def state(self):
        """Gets the state of this APIAccess.  # noqa: E501

        Pending or approved state  # noqa: E501

        :return: The state of this APIAccess.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this APIAccess.

        Pending or approved state  # noqa: E501

        :param state: The state of this APIAccess.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def created_on(self):
        """Gets the created_on of this APIAccess.  # noqa: E501

        Epoch/Unix time stamp when the approval decision was created   # noqa: E501

        :return: The created_on of this APIAccess.  # noqa: E501
        :rtype: int
        """
        return self._created_on

    @created_on.setter
    def created_on(self, created_on):
        """Sets the created_on of this APIAccess.

        Epoch/Unix time stamp when the approval decision was created   # noqa: E501

        :param created_on: The created_on of this APIAccess.  # noqa: E501
        :type: int
        """

        self._created_on = created_on

    @property
    def enabled(self):
        """Gets the enabled of this APIAccess.  # noqa: E501

        Flag disables access to an API for organization or application  # noqa: E501

        :return: The enabled of this APIAccess.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this APIAccess.

        Flag disables access to an API for organization or application  # noqa: E501

        :param enabled: The enabled of this APIAccess.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(APIAccess, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, APIAccess):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
