
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-15T14:02:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ac1d874aaaa5ba1fa39a708984a91c9930cf871",
 "version": "0.4.110"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
