- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - keystone-dsvm-py3-functional
        - keystone-dsvm-py3-functional-federation-opensuse15:
            voting: false
        - keystone-dsvm-py3-functional-federation-opensuse15-k2k
    gate:
      jobs:
        - keystone-dsvm-py3-functional
        - keystone-dsvm-py3-functional-federation-opensuse15-k2k
