#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['argparse']

setup(name='mvm_control',
      version='1.0.0',
      description='Simple command line tool to access a MVM ESP32 via the serial port',
      author='Bryerton Shaw',
      author_email='bryerton@triumf.ca',
      url='https://github.com/bryerton/mvm-control',
      py_modules=['mvm_control'],
      install_requires=install_requires,
     )
