# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from api.tree_leaf_type_api import TreeLeafTypeApi  # noqa: E501
from tator.rest import ApiException


class TestTreeLeafTypeApi(unittest.TestCase):
    """TreeLeafTypeApi unit test stubs"""

    def setUp(self):
        self.api = api.tree_leaf_type_api.TreeLeafTypeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_tree_leaf_type_list_api(self):
        """Test case for create_tree_leaf_type_list_api

        """
        pass

    def test_destroy_entity_type_tree_leaf_attr(self):
        """Test case for destroy_entity_type_tree_leaf_attr

        """
        pass

    def test_partial_update_entity_type_tree_leaf_attr(self):
        """Test case for partial_update_entity_type_tree_leaf_attr

        """
        pass

    def test_retrieve_entity_type_tree_leaf_attr(self):
        """Test case for retrieve_entity_type_tree_leaf_attr

        """
        pass

    def test_retrieve_tree_leaf_type_list_api(self):
        """Test case for retrieve_tree_leaf_type_list_api

        """
        pass

    def test_update_entity_type_tree_leaf_attr(self):
        """Test case for update_entity_type_tree_leaf_attr

        """
        pass


if __name__ == '__main__':
    unittest.main()
