# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from models.body43 import Body43  # noqa: E501
from tator.rest import ApiException


class TestBody43(unittest.TestCase):
    """Body43 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody43(self):
        """Test Body43"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tator.models.body43.Body43()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
