[tool.poetry]
name = "openqlab"
version = "0.1.12"
description = "An open-source collection of tools for quantum-optics experiments"
authors = [
"Jan Petermann <jpeterma@physnet.uni-hamburg.de>",
"Christian Darsow-Fromm <cdarsowf@physnet.uni-hamburg.de>",
]
maintainers = [
"Christian Darsow-Fromm <cdarsowf@physnet.uni-hamburg.de>",
"Jan Petermann <jpeterma@physnet.uni-hamburg.de>",
]
readme = "README.md"
repository = "https://gitlab.com/las-nq/openqlab"
documentation = "https://las-nq-serv.physnet.uni-hamburg.de/python/openqlab/"

[tool.poetry.dependencies]
python = "^3.6"
pyserial = "*"
numpy = "*"
scipy = ">=1.1.0"
pandas = "<1.0"
matplotlib = "*"
tabulate = "*"
pytimeparse = "*"
pytz = "*"
pathlib = "*"
psutil = "*"
statsmodels = "*"
jsonpickle = "*"
multiprocess = "*"
dill = "*"
requests = "*"
six = ">=1.12.0"
python-dateutil = ">=2.7.5"
eml-parser = ">=1.11"
DateTime = "*"
pyvisa = "*"
pyvisa-py = "*"
tables = "*"
cufflinks = "*"


[tool.poetry.dev-dependencies]
recommonmark = "*"
docutils = "*"
sphinx-markdown-tables = "*"
pytest = "*"
pytest-cov = ">=2.5.1"
sphinx-rtd-theme = "*"
twine = "*"
mypy = "*"
pylint = "*"
sphinx = "*"
pipenv = "*"
black = "==19.10b0"
pre-commit = "*"
pydocstyle = "*"
isort = "*"
seed-isort-config = "*"
ipython = "*"
rope = "*"
jupyterlab = "*"
py2exe = "*" # Needed for tk on Windows
flake8 = "^3.7.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
