[tool.poetry]
name = "download_google_images"
version = "0.1.0"
description = ""
authors = ["Adarsh1999 <adarshguptamaurya@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
download-google-images = "download_google_images.main:app"

[tool.poetry.dependencies]
python = "^3.7"
typer = {extras = ["all"], version = "^0.1.1"}
selenium = "^3.141.0"
pillow = "^7.1.1"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
