[tool.poetry]
name = "stirfried"
version = "0.6.0"
description = "Socket.IO server to schedule Celery tasks from clients in real-time."
authors = ["Korijn van Golen <korijn@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
celery = "^4.4.0"
python-socketio = "^4.4.0"
redis = "^3.4.1"
uvicorn = "^0.11.3"
aioredis = "^1.3.1"
msgpack-python = "^0.5.6"
starlette = "^0.13.2"

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
black = "^19.10b0"
pep8-naming = "^0.9.1"
flake8-black = "^0.1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
