[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 79

[tool.isort]
line_length = 79
indent = '    '
multi_line_output = 3
include_trailing_comma = true

[tool.poetry]
name = "toml-sort"
version = "0.18.0"
description = "Toml sorting library"
authors = ["Sam Roeca <samuel.roeca@gmail.com>"]
readme = "README.md"
homepage = "https://toml-sort.readthedocs.io/en/latest/"
repository = "https://github.com/pappasam/toml-sort"
keywords = ["toml", "sort", "cli", "unix", "utility"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Topic :: Software Development :: Code Generators",
  "Topic :: Utilities",
  "Typing :: Typed",
]
include = ["README.md"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
tomlkit = ">=0.5.8"
click = ">=7.0"

[tool.poetry.dev-dependencies]
pylint = "^2.3"
black = {version = "^19.10b0", allow-prereleases = true}
mypy = "^0.720.0"
pre-commit = "^1.18"
tox = "^3.13"
pytest = "^5.0"
tox-asdf = "^0.1.0"
isort = "^4.3.21"
sphinx = "^2.2.2"
sphinx-rtd-theme = "^0.4.3"
m2r = "^0.2.1"
sphinx-click = "^2.3.1"

[tool.poetry.scripts]
toml-sort = 'toml_sort.cli:cli'

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py36,py37,py38
isolated_build = true
skipsdist = true
[testenv]
platform = linux
whitelist_externals = poetry
skip_install = true
commands =
  poetry install
  poetry run black --check --diff toml_sort tests
  poetry run mypy toml_sort
  poetry run pylint toml_sort tests
  poetry run pytest -vv
"""
