[tool.poetry]
name = "pydantic_openapi_ng"
version = "0.2.1"
description = "Generate OpenAPI schema from pydantic models"
authors = ["Yury Blagoveshchenskiy <yurathestorm@gmail.com>", "Sinkerine <i@15cm.net>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.6"
pydantic = "*"
inflection = "*"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
openapigen = 'pydantic_openapi_ng.command_line:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
