# coding: utf-8

"""
    API Manager API v1.3

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3.0
    Contact: support@axway.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.custom_property_permission import CustomPropertyPermission  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomPropertyPermission(unittest.TestCase):
    """CustomPropertyPermission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomPropertyPermission(self):
        """Test CustomPropertyPermission"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.custom_property_permission.CustomPropertyPermission()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
