#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['flit', 'flit.vcs', 'flit.vendorized', 'flit.vendorized.readme']

package_data = \
{'': ['*'], 'flit': ['license_templates/*']}

install_requires = \
['dflit_core>=2.3.0.1', 'requests', 'docutils', 'pytoml']

extras_require = \
{":python_version in '3.3 3.4 3.5'": ['zipfile36'],
 'doc': ['sphinx', 'sphinxcontrib_github_alt', 'pygments-github-lexers'],
 'installfrom': ['requests_download'],
 'test': ['testpath', 'responses', 'pytest>=2.7.3', 'pytest-cov']}

entry_points = \
{'console_scripts': ['flit = flit:main']}

setup(name='dflit',
      version='2.3.0.1',
      description='A simple packaging tool for simple packages.',
      author='David Fritzsche / flit by Thomas Kluyver',
      author_email='david.fritzsche@mvua.de',
      url='https://github.com/davidfritzsche/dflit',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.5',
     )
