# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2020-04-20 16:55:13 UTC
from __future__ import unicode_literals
import datetime

version = "3.2.1"
githash = "ba3734222a40f4c2864c375c6639f32cd9df06cd"


major = 3
minor = 2
bugfix = 1

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2020, 4, 20, 16, 55, 13)
debug = False

astropy_helpers_version = ""
