- project:
    templates:
      - openstack-python-jobs-no-constraints
      - openstack-python35-jobs-no-constraints
    check:
      jobs:
        - dib-nodepool-functional-openstack-gentoo-src:
            voting: false
        - dib-nodepool-functional-openstack-centos-7-src
        - dib-nodepool-functional-openstack-fedora-30-src
        - dib-nodepool-functional-openstack-ubuntu-xenial-src
        - dib-nodepool-functional-openstack-ubuntu-bionic
        - dib-nodepool-functional-openstack-ubuntu-bionic-src
    gate:
      jobs:
        - dib-nodepool-functional-openstack-centos-7-src
        - dib-nodepool-functional-openstack-fedora-30-src
        - dib-nodepool-functional-openstack-ubuntu-xenial-src
        - dib-nodepool-functional-openstack-ubuntu-bionic
        - dib-nodepool-functional-openstack-ubuntu-bionic-src
    experimental:
      jobs:
        - dib-nodepool-functional-openstack-debian-stretch-src
        - dib-nodepool-functional-openstack-debian-buster-src
        - dib-nodepool-functional-openstack-opensuse-15-src
        - dib-nodepool-functional-openstack-opensuse-tumbleweed-src
