
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-17T13:36:09+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "98e5452cab2024f16483a291a8572a2fe909a180",
 "version": "0.3.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
