# https://docs.travis-ci.com/user/
language: python

python:
- 3.4
- 3.5
- 3.6
- 3.7
- 3.8

# required for python >= 3.7
dist: xenial

env:
- PIPENV_IGNORE_VIRTUALENVS=1

install:
- pip install --upgrade pipenv>=2018.10.9
- pipenv sync --dev
- pipenv graph

script:
- pipenv run pylint pylint_import_requirements
- pipenv run pytest --cov=pylint_import_requirements --cov-report=term-missing
