
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-24T11:30:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3af2e48e47476c790865c0e37338462659108d71",
 "version": "2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
