[tool.poetry]
name = "gandi-update-dns"
version = "0.1.6"
description = "Yet another tool to update DNS zone in gandi provider"
authors = ["Aloha68 <dev@aloha.im>"]
license = "ISC"
readme = "README.md"
homepage = "https://gitlab.com/aloha68/gandi-update-dns"
repository = "https://gitlab.com/aloha68/gandi-update-dns"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: System Administrators",
    "Operating System :: POSIX :: Linux",
    "Topic :: Internet :: Name Service (DNS)",
    "Topic :: System :: Networking",
    "Topic :: System :: Systems Administration",
]

[tool.poetry.dependencies]
python = "^3.4"
xdg = "^3.0"
send-sms-freemobile = {version = "^0.1.0",optional = true}

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
send-sms = ["send-sms-freemobile"]

[tool.poetry.scripts]
gandi-update-dns = 'gandi_update_dns:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
