model_config:
  unimodal_text:
    metrics:
    - accuracy
    losses:
    - type: cross_entropy

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: ${training.max_updates}

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

training:
  batch_size: 128
  lr_scheduler: true
  max_updates: 22000
  monitored_metric: hateful_memes/accuracy
  pretrained_mapping:
    base: base
