stages:
  - pre_testing
  - testing
  - post_testing
  - publish

before_script:
  - apt-get update -qy
  - pip install pip -U

flake8:
    image: python:3
    stage: pre_testing
    before_script:
      - pip install flake8
      # Help flake8 to find the Python files without .py extension.
      - find . -name '*.py' >> files.txt
      - sort -u files.txt | tee files.processed
    script:
        - python -m flake8 --statistics --count $(cat files.processed) --verbose
    after_script:
        - wc -l files.processed

tests:
    image: python:3
    stage: testing
    coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
    before_script:
      - pip3 install virtualenv
      - virtualenv -p python3 faraday_venv
      - source faraday_venv/bin/activate
      - pip3 install pytest pytest-xdist pytest-cov faradaysec
      - pip uninstall faraday-plugins -y # we need to install fardaysec for marshmallow schemas, we remove plugins frsom pipy
      - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/faradaysec/support/report-collection.git
    script:
      - source faraday_venv/bin/activate
      - python3 setup.py install
      - pytest tests --capture=sys -v --cov=faraday_plugins --color=yes --disable-warnings


test_performance:
    image: python:3
    stage: post_testing
    coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
    allow_failure: true
    before_script:
      - pip3 install virtualenv
      - virtualenv -p python3 faraday_venv
      - source faraday_venv/bin/activate
      - pip3 install pytest pytest-xdist pytest-cov pytest-benchmark faradaysec
      - pip uninstall faraday-plugins -y # we need to install fardaysec for marshmallow schemas, we remove plugins frsom pipy
      - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/faradaysec/support/report-collection.git
    script:
      - source faraday_venv/bin/activate
      - python3 setup.py install
      - pytest tests --capture=sys -v --cov=faraday_plugins --color=yes --disable-warnings --performance
    only:
      - develop

publish_pypi:
    image: python:3
    stage: publish
    before_script:
      - pip3 install virtualenv
      - virtualenv -p python3 faraday_venv
      - source faraday_venv/bin/activate
      - pip install twine
    script:
      - python setup.py sdist bdist_wheel
      - twine upload dist/* -u $TWINE_USERNAME -p $TWINE_PASSWORD

    only:
      variables:
        - $CI_COMMIT_TAG =~ /^v[0-9.]+$/
