
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-23T12:48:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c717f414b7b434eb157ce23ba78a1284082df4d",
 "version": "1.8.0.post.dev49"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
