[tool.poetry]
name = "proto-square-api"
version = "0.1.0"
description = ""
authors = ["Jerome Leclanche <jerome@leclan.ch>"]

[tool.poetry.dependencies]
python = "^3.8"
protobuf = "^3.11.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
use-tabs = true
