[tool.poetry]
name = "sdesk"
version = "0.1.0"
description = "ScienceDesk helper library"
authors = ["ScienceDesk GmbH <github@sciencedesk.net>"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
