# coding: utf-8

"""
    Flomvarsel API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import varsom_flood_client
from models.cause import Cause  # noqa: E501
from varsom_flood_client.rest import ApiException


class TestCause(unittest.TestCase):
    """Cause unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCause(self):
        """Test Cause"""
        # FIXME: construct object with mandatory attributes with example values
        # model = varsom_flood_client.models.cause.Cause()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
