# coding: utf-8

"""
    Flomvarsel API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import varsom_flood_client
from models.alert import Alert  # noqa: E501
from varsom_flood_client.rest import ApiException


class TestAlert(unittest.TestCase):
    """Alert unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlert(self):
        """Test Alert"""
        # FIXME: construct object with mandatory attributes with example values
        # model = varsom_flood_client.models.alert.Alert()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
