# Base Configuration file for artellapipe-tools-modelchecker for Plot Twist

# Defines icon of the tool
icon: modelchecker

# URL to tool documentation web page
help_url: https://plot-twist-short-film.github.io/plottwist-docs/pipeline/pipeline/tools/modelchecker/

# Defines whether this needs Kitsu data to work or not
kitsu_login: False

pyblish_plugins:
  CollectGeometry: {}
  CollectPlotTwistProxyMesh: {}
  ValidateStudentLicense:
    optional: True
  ValidateDisplayLayers:
    optional: True
  ValidateNoShadersInScene:
    optional: True
  ValidateCleanUnknownNodes:
    optional: True
  ValidateCleanUnusedPlugins:
    optional: True
  ValidateCleanTurtleNodes:
    optional: True
  ValidateCleanGarbageNodes:
    optional: True
  ValidateLamina:
    optional: True
  ValidateNGons:
    optional: True
  ValidateNonManifoldEdges:
    optional: True
  ValidateOpenEdges:
    optional: True
  ValidateStarLike:
    optional: True
  ValidateTriangles:
    optional: True
  ValidateNormals:
    optional: True
  ValidateZeroAreaFaces:
    optional: True
  ValidateZeroLengthEdges:
    optional: True
  ValidateCleanHistory:
    optional: True
  ValidateGeometryDisplayLayers:
    optional: True
  ValidateGeometrySmoothPreview:
    optional: True
  ValidateEmptyGroups:
    optional: True
  ValidateGeometryShaders:
    optional: True
  ValidateParentGeometry:
    optional: True
  ValidateUncenteredPivots:
    optional: True
  ValidateUnfrozenTransforms:
    optional: True
  ValidatePlotTwistModelingHierarchy:
    optional: True
  ValidatePlotTwistProxyMesh:
    optional: True