[tool.poetry]
name = "isingm"
version = "1.1.1"
description = "A pythonic Ising model simulation"
authors = ["pacidus <pacidus@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/Pacidus/isingm"
keywords = ["physics", "ising", "montecarlo", "ising model", "metropolis algorithm"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.18.2"
matplotlib = "^3.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
