# coding: utf-8

"""
    Snøskredvarsel API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v5.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import varsom_avalanche_client
from api.region_api import RegionApi  # noqa: E501
from varsom_avalanche_client.rest import ApiException


class TestRegionApi(unittest.TestCase):
    """RegionApi unit test stubs"""

    def setUp(self):
        self.api = api.region_api.RegionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_region_all(self):
        """Test case for region_all

        """
        pass

    def test_region_get(self):
        """Test case for region_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
