[tool.poetry]
name = "pspipe"
version = "0.1.3"
description = "Power spectra pipeline for Cosmic Dawn, Epoch of Reionization radio interferometric experiments"
authors = ["\"Florent Mertens\" <\"florent.mertens@gmail.com\">"]
repository = "https://gitlab.com/flomertens/pspipe/"
readme = 'README.md'

[tool.poetry.dependencies]
python = "^3.6"
toml = "^0.10"
python-casacore = "^3.0"
astropy = "^4.0"
matplotlib = "^3.0"
tables = "^3.2"
tabulate = "^0.8"
nenucal = "^0.1"
ps-eor = "^0.7"
# nenucal = {path = "/home/flo/Developpement/cd-eor/nenucal-cd"}
# ps-eor = {path = "/home/flo/Developpement/cd-eor/ps_eor"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.8.1"

[tool.poetry.scripts]
psdb = "pspipe.tools.psdb:main"
pspipe = "pspipe.tools.pspipe:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

