version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.7
      - test-3.8
jobs:
  test-3.6: &test-template
    docker:
      - image: python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install tldextract
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m unittest
  test-3.7:
    <<: *test-template
    docker:
      - image: python:3.7
  test-3.8:
    <<: *test-template
    docker:
      - image: python:3.8
