# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from spaceone.api.statistics.v1 import history_pb2 as spaceone_dot_api_dot_statistics_dot_v1_dot_history__pb2


class HistoryStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.query = channel.unary_unary(
                '/spaceone.api.statistics.v1.History/query',
                request_serializer=spaceone_dot_api_dot_statistics_dot_v1_dot_history__pb2.QueryHistoryRequest.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_statistics_dot_v1_dot_history__pb2.HistoryInfo.FromString,
                )
        self.diff = channel.unary_unary(
                '/spaceone.api.statistics.v1.History/diff',
                request_serializer=spaceone_dot_api_dot_statistics_dot_v1_dot_history__pb2.DiffHistoryRequest.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_statistics_dot_v1_dot_history__pb2.DiffInfo.FromString,
                )


class HistoryServicer(object):
    """Missing associated documentation comment in .proto file"""

    def query(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def diff(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HistoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'query': grpc.unary_unary_rpc_method_handler(
                    servicer.query,
                    request_deserializer=spaceone_dot_api_dot_statistics_dot_v1_dot_history__pb2.QueryHistoryRequest.FromString,
                    response_serializer=spaceone_dot_api_dot_statistics_dot_v1_dot_history__pb2.HistoryInfo.SerializeToString,
            ),
            'diff': grpc.unary_unary_rpc_method_handler(
                    servicer.diff,
                    request_deserializer=spaceone_dot_api_dot_statistics_dot_v1_dot_history__pb2.DiffHistoryRequest.FromString,
                    response_serializer=spaceone_dot_api_dot_statistics_dot_v1_dot_history__pb2.DiffInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spaceone.api.statistics.v1.History', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class History(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.statistics.v1.History/query',
            spaceone_dot_api_dot_statistics_dot_v1_dot_history__pb2.QueryHistoryRequest.SerializeToString,
            spaceone_dot_api_dot_statistics_dot_v1_dot_history__pb2.HistoryInfo.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def diff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.statistics.v1.History/diff',
            spaceone_dot_api_dot_statistics_dot_v1_dot_history__pb2.DiffHistoryRequest.SerializeToString,
            spaceone_dot_api_dot_statistics_dot_v1_dot_history__pb2.DiffInfo.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
