
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "2dc993e4ad4ca6f141700a05bb09ca7889e499d8",
 "version": "2294"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
