[tool.poetry]
name = "viz-python-lib"
version = "0.1.0"
description = "python library for VIZ blockchain"
authors = ["Vladimir Kamarzin <vvk@vvk.pp.ru>"]
license = "MIT"
packages = [
    { include = "viz" },
    { include = "vizapi" },
    { include = "vizbase" },
]

[tool.poetry.dependencies]
python = "^3.6.1"
graphenelib = "^1.2.0"
toolz = "^0.10.0"
funcy = "^1.14"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
