[tool.poetry]
name = "coronatank"
version = "0.1.0"
description = "A small tank game based on pygame."
authors = ["Sylvain Roy <sylvain.roy@m4x.org>"]

[tool.poetry.dependencies]
python = "^3.7.7"
pygame = "^1.9.6"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
