parameters:
  dbxdeploy:
    browser:
      path: 'c:/Program Files (x86)/Google/Chrome/Application/chrome.exe'
      arguments: ['-d', '{runUrl}']
    git:
      baseDir: '.'
      devBranch: 'master'
    source:
      notebooks:
        baseDir: 'src'
        patterns: '%dbxdeploy.notebooks.paths%'
        consumersPatterns: '%dbxdeploy.notebooks.consumerPaths%'
    target:
      workspaceBaseDir: '%dbxdeploy.databricks.projectRoot%'
      whlBaseDir: '%dbxdeploy.databricks.whlBaseDir%'
    export:
      forceEndFileNewline: True # @deprecated, set to False in 0.10.0
    databricks: # @deprecated, to be removed in 0.10.0
      projectRoot: '/{currentBranch}'
      whlBaseDir: 'dbfs:/FileStore/jars'
    notebooks: # @deprecated, to be removed in 0.10.0
      paths: ['**/*.py']
      consumerPaths: ['**/*.consumer.py']

services:
  dbxdeploy.cluster.ClusterRestarter:
    arguments:
      - '%dbxdeploy.databricks.clusterId%'
      - '@consolebundle.logger'
      - '@dbxdeploy.databricksApi'

  dbxdeploy.deploy.WorkingDirFactory:

  dbxdeploy.deploy.workingDir:
    class: pathlib.Path
    factory: ['@dbxdeploy.deploy.WorkingDirFactory', 'create']

  dbxdeploy.deploy.CurrentAndReleaseDeployer:

  dbxdeploy.deploy.Deployer:
    arguments:
      - '@dbxdeploy.deploy.workingDir'

  dbxdeploy.deploy.DeployCommand:
    tags:
      - 'console.command'

  dbxdeploy.deploy.DeployerJobSubmitter:
    arguments:
      - '@dbxdeploy.deploy.workingDir'

  dbxdeploy.deploy.DeployJobSubmitCommand:
    arguments:
      - '@consolebundle.logger'
    tags:
      - 'console.command'

  dbxdeploy.deploy.Releaser:
    arguments:
      - '@dbxdeploy.deploy.workingDir'
      - '@dbxdeploy.target.workspaceBaseDir'
      - '@consolebundle.logger'

  dbxdeploy.deploy.ReleaseCommand:
    tags:
      - 'console.command'

  dbxdeploy.git.CurrentBranchResolver:
    arguments:
      - '%dbxdeploy.git.baseDir%'

  dbxdeploy.package.PackageMetadataLoader:

  dbxdeploy.whl.WhlBuilder:

  dbxdeploy.whl.RequirementsLineConverter:

  dbxdeploy.whl.WhlUploader:
    arguments:
      - '@consolebundle.logger'
      - '@dbxdeploy.databricksApi'

  dbxdeploy.whl.WhlDeployer:
    arguments:
      - '@dbxdeploy.deploy.workingDir'
      - '%dbxdeploy.target.whlBaseDir%'
      - '@consolebundle.logger'

  dbxdeploy.dbc.DbcCreator:
    arguments:
      - '@dbxdeploy.deploy.workingDir'
      - '@consolebundle.logger'

  dbxdeploy.dbc.DbcNotebookConverter:

  dbxdeploy.dbc.DbcUploader:
    arguments:
      - '@dbxdeploy.databricksApi'

  dbxdeploy.dbc.PathsPreparer:

  dbxdeploy.dbc.CommandsConverter:
    arguments:
      - '%dbxdeploy.export.forceEndFileNewline%'

  dbxdeploy.dbc.CommandConverter:
    arguments:
      - '%dbxdeploy.target.whlBaseDir%'

  dbxdeploy.notebook.NotebooksDeployer:
    arguments:
      - '@dbxdeploy.target.workspaceBaseDir'
      - '%dbxdeploy.target.whlBaseDir%'
      - '@consolebundle.logger'
      - '@dbxdeploy.databricksApi'

  dbxdeploy.job.JobsDeleter:
    arguments:
      - '@consolebundle.logger'
      - '@dbxdeploy.databricksApi'

  dbxdeploy.job.JobsDeleterCommand:
    arguments:
      - '@consolebundle.logger'
    tags:
      - 'console.command'

  dbxdeploy.job.JobCreator:
    arguments:
      - '%dbxdeploy.databricks.clusterId%'
      - '@dbxdeploy.target.workspaceBaseDir'
      - '@consolebundle.logger'
      - '@dbxdeploy.databricksApi'

  dbxdeploy.job.JobsCreatorAndRunner:
    arguments:
      - '@consolebundle.logger'
      - '@dbxdeploy.databricksApi'

  dbxdeploy.job.JobSubmitter:
    arguments:
      - '%dbxdeploy.databricks.clusterId%'
      - '@dbxdeploy.target.workspaceBaseDir'
      - '%dbxdeploy.browser%'
      - '@consolebundle.logger'
      - '@dbxdeploy.databricksApi'

  dbxdeploy.job.RunsGetter:
    arguments:
      - '%dbxdeploy.databricks.clusterId%'
      - '@dbxdeploy.target.workspaceBaseDir'
      - '@dbxdeploy.databricksApi'

  dbxdeploy.job.NotebookKiller:
    arguments:
      - '@consolebundle.logger'
      - '@dbxdeploy.databricksApi'

  dbxdeploy.databricksApi:
    class: databricks_api.databricks.DatabricksAPI
    autowire: False
    arguments:
      -
        host: '%dbxdeploy.databricks.host%'
        token: '%dbxdeploy.databricks.token%'

  dbxdeploy.notebook.CurrentDirectoryUpdater:
    arguments:
      - '@dbxdeploy.target.workspaceBaseDir'
      - '%dbxdeploy.git.devBranch%'
      - '@consolebundle.logger'
      - '@dbxdeploy.databricksApi'

  dbxdeploy.workspace.WorkspaceBaseDirFactory:
    arguments:
      - '%dbxdeploy.target.workspaceBaseDir%'

  dbxdeploy.target.workspaceBaseDir:
    class: pathlib.PurePosixPath
    factory: ['@dbxdeploy.workspace.WorkspaceBaseDirFactory', 'create']

  dbxdeploy.workspace.WorkspaceImporter:
    arguments:
      - '@dbxdeploy.databricksApi'

  dbxdeploy.workspace.WorkspaceExporter:
    arguments:
      - '@dbxdeploy.databricksApi'

  dbxdeploy.workspace.WorkspaceExportCommand:
    arguments:
      - '@dbxdeploy.target.workspaceBaseDir'
      - '@dbxdeploy.deploy.workingDir'
      - '%dbxdeploy.source.notebooks.baseDir%'
      - '@consolebundle.logger'
    tags:
      - 'console.command'

  dbxdeploy.workspace.DbcFilesHandler:

  dbxdeploy.notebook.NotebooksLocator:
    arguments:
      - '@dbxdeploy.deploy.workingDir'
      - '%dbxdeploy.source.notebooks.patterns%'
      - '%dbxdeploy.source.notebooks.consumersPatterns%'

  dbxdeploy.notebook.RelativePathResolver:
    arguments:
      - '%dbxdeploy.source.notebooks.baseDir%'

  dbxdeploy.notebook.converter.JinjaTemplateLoader:

  dbxdeploy.notebook.converter.DbcScriptRenderer:

  dbxdeploy.notebook.converter.CellsExtractor:

  dbxdeploy.notebook.converter.DatabricksNotebookConverter:
