
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-03-26T21:54:55-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "062d0363c6c1366882d1a5fb2aa6db98f9d35949",
 "version": "1.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
