all:
  hosts:
    client-host: {ansible_host: 51.75.13.122}
    icinga-host: {ansible_host: 51.68.42.39}
    letsencrypt-host: {ansible_host: 51.83.111.25}
    letsencryptstaging-host: {ansible_host: 51.77.229.204}
    openvpnclient-host: {ansible_host: 51.77.207.46}
    ownca-host: {ansible_host: 51.75.199.176}
    owncanotweb-host: {ansible_host: 51.68.115.80}
    website-host: {ansible_host: 51.77.205.126}
