
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-19T13:26:08-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2b86de3f0620e6c12a8d89c73d4ccef4a7d9a33",
 "version": "2020.4.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
