# Autogenerated by Astropy-affiliated package skypy's setup.py on 2020-04-17 12:07:13 UTC
from __future__ import unicode_literals
import datetime

version = "0.1"
githash = "54de691341a23769b60acddffb63d97089d71a61"


major = 0
minor = 1
bugfix = 0

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2020, 4, 17, 12, 7, 13)
debug = False

astropy_helpers_version = "3.2.1"
